/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblemployerCompanyinfo implements Serializable {

    private static final long serialVersionUID = 1256340101;

    private Integer   companyid;
    private UInteger  companylogo;
    private Byte      isshowlogo;
    private UInteger  companylogopending;
    private Byte      isapproved;
    private String    companyname;
    private Byte      companysizeid;
    private String    aboutlink;
    private String    companyprofile;
    private String    whyworkwithus;
    private String    address;
    private String    district;
    private Integer   cityid;
    private Short     countryid;
    private String    telephone;
    private String    cellphone;
    private String    faxnumber;
    private String    website;
    private String    profilebasename;
    private String    contactname;
    private String    contactemail;
    private Byte      contactmethodid;
    private String    contactposition;
    private Byte      isupgradeprofile;
    private Byte      isdeleteprofile;
    private Byte      isallowuseredit;
    private Byte      allowredirect;
    private Timestamp lastdateupdated;

    public TblemployerCompanyinfo() {}

    public TblemployerCompanyinfo(TblemployerCompanyinfo value) {
        this.companyid = value.companyid;
        this.companylogo = value.companylogo;
        this.isshowlogo = value.isshowlogo;
        this.companylogopending = value.companylogopending;
        this.isapproved = value.isapproved;
        this.companyname = value.companyname;
        this.companysizeid = value.companysizeid;
        this.aboutlink = value.aboutlink;
        this.companyprofile = value.companyprofile;
        this.whyworkwithus = value.whyworkwithus;
        this.address = value.address;
        this.district = value.district;
        this.cityid = value.cityid;
        this.countryid = value.countryid;
        this.telephone = value.telephone;
        this.cellphone = value.cellphone;
        this.faxnumber = value.faxnumber;
        this.website = value.website;
        this.profilebasename = value.profilebasename;
        this.contactname = value.contactname;
        this.contactemail = value.contactemail;
        this.contactmethodid = value.contactmethodid;
        this.contactposition = value.contactposition;
        this.isupgradeprofile = value.isupgradeprofile;
        this.isdeleteprofile = value.isdeleteprofile;
        this.isallowuseredit = value.isallowuseredit;
        this.allowredirect = value.allowredirect;
        this.lastdateupdated = value.lastdateupdated;
    }

    public TblemployerCompanyinfo(
        Integer   companyid,
        UInteger  companylogo,
        Byte      isshowlogo,
        UInteger  companylogopending,
        Byte      isapproved,
        String    companyname,
        Byte      companysizeid,
        String    aboutlink,
        String    companyprofile,
        String    whyworkwithus,
        String    address,
        String    district,
        Integer   cityid,
        Short     countryid,
        String    telephone,
        String    cellphone,
        String    faxnumber,
        String    website,
        String    profilebasename,
        String    contactname,
        String    contactemail,
        Byte      contactmethodid,
        String    contactposition,
        Byte      isupgradeprofile,
        Byte      isdeleteprofile,
        Byte      isallowuseredit,
        Byte      allowredirect,
        Timestamp lastdateupdated
    ) {
        this.companyid = companyid;
        this.companylogo = companylogo;
        this.isshowlogo = isshowlogo;
        this.companylogopending = companylogopending;
        this.isapproved = isapproved;
        this.companyname = companyname;
        this.companysizeid = companysizeid;
        this.aboutlink = aboutlink;
        this.companyprofile = companyprofile;
        this.whyworkwithus = whyworkwithus;
        this.address = address;
        this.district = district;
        this.cityid = cityid;
        this.countryid = countryid;
        this.telephone = telephone;
        this.cellphone = cellphone;
        this.faxnumber = faxnumber;
        this.website = website;
        this.profilebasename = profilebasename;
        this.contactname = contactname;
        this.contactemail = contactemail;
        this.contactmethodid = contactmethodid;
        this.contactposition = contactposition;
        this.isupgradeprofile = isupgradeprofile;
        this.isdeleteprofile = isdeleteprofile;
        this.isallowuseredit = isallowuseredit;
        this.allowredirect = allowredirect;
        this.lastdateupdated = lastdateupdated;
    }

    public Integer getCompanyid() {
        return this.companyid;
    }

    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    public UInteger getCompanylogo() {
        return this.companylogo;
    }

    public void setCompanylogo(UInteger companylogo) {
        this.companylogo = companylogo;
    }

    public Byte getIsshowlogo() {
        return this.isshowlogo;
    }

    public void setIsshowlogo(Byte isshowlogo) {
        this.isshowlogo = isshowlogo;
    }

    public UInteger getCompanylogopending() {
        return this.companylogopending;
    }

    public void setCompanylogopending(UInteger companylogopending) {
        this.companylogopending = companylogopending;
    }

    public Byte getIsapproved() {
        return this.isapproved;
    }

    public void setIsapproved(Byte isapproved) {
        this.isapproved = isapproved;
    }

    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    public Byte getCompanysizeid() {
        return this.companysizeid;
    }

    public void setCompanysizeid(Byte companysizeid) {
        this.companysizeid = companysizeid;
    }

    public String getAboutlink() {
        return this.aboutlink;
    }

    public void setAboutlink(String aboutlink) {
        this.aboutlink = aboutlink;
    }

    public String getCompanyprofile() {
        return this.companyprofile;
    }

    public void setCompanyprofile(String companyprofile) {
        this.companyprofile = companyprofile;
    }

    public String getWhyworkwithus() {
        return this.whyworkwithus;
    }

    public void setWhyworkwithus(String whyworkwithus) {
        this.whyworkwithus = whyworkwithus;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public Integer getCityid() {
        return this.cityid;
    }

    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    public Short getCountryid() {
        return this.countryid;
    }

    public void setCountryid(Short countryid) {
        this.countryid = countryid;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getCellphone() {
        return this.cellphone;
    }

    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    public String getFaxnumber() {
        return this.faxnumber;
    }

    public void setFaxnumber(String faxnumber) {
        this.faxnumber = faxnumber;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getProfilebasename() {
        return this.profilebasename;
    }

    public void setProfilebasename(String profilebasename) {
        this.profilebasename = profilebasename;
    }

    public String getContactname() {
        return this.contactname;
    }

    public void setContactname(String contactname) {
        this.contactname = contactname;
    }

    public String getContactemail() {
        return this.contactemail;
    }

    public void setContactemail(String contactemail) {
        this.contactemail = contactemail;
    }

    public Byte getContactmethodid() {
        return this.contactmethodid;
    }

    public void setContactmethodid(Byte contactmethodid) {
        this.contactmethodid = contactmethodid;
    }

    public String getContactposition() {
        return this.contactposition;
    }

    public void setContactposition(String contactposition) {
        this.contactposition = contactposition;
    }

    public Byte getIsupgradeprofile() {
        return this.isupgradeprofile;
    }

    public void setIsupgradeprofile(Byte isupgradeprofile) {
        this.isupgradeprofile = isupgradeprofile;
    }

    public Byte getIsdeleteprofile() {
        return this.isdeleteprofile;
    }

    public void setIsdeleteprofile(Byte isdeleteprofile) {
        this.isdeleteprofile = isdeleteprofile;
    }

    public Byte getIsallowuseredit() {
        return this.isallowuseredit;
    }

    public void setIsallowuseredit(Byte isallowuseredit) {
        this.isallowuseredit = isallowuseredit;
    }

    public Byte getAllowredirect() {
        return this.allowredirect;
    }

    public void setAllowredirect(Byte allowredirect) {
        this.allowredirect = allowredirect;
    }

    public Timestamp getLastdateupdated() {
        return this.lastdateupdated;
    }

    public void setLastdateupdated(Timestamp lastdateupdated) {
        this.lastdateupdated = lastdateupdated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblemployerCompanyinfo (");

        sb.append(companyid);
        sb.append(", ").append(companylogo);
        sb.append(", ").append(isshowlogo);
        sb.append(", ").append(companylogopending);
        sb.append(", ").append(isapproved);
        sb.append(", ").append(companyname);
        sb.append(", ").append(companysizeid);
        sb.append(", ").append(aboutlink);
        sb.append(", ").append(companyprofile);
        sb.append(", ").append(whyworkwithus);
        sb.append(", ").append(address);
        sb.append(", ").append(district);
        sb.append(", ").append(cityid);
        sb.append(", ").append(countryid);
        sb.append(", ").append(telephone);
        sb.append(", ").append(cellphone);
        sb.append(", ").append(faxnumber);
        sb.append(", ").append(website);
        sb.append(", ").append(profilebasename);
        sb.append(", ").append(contactname);
        sb.append(", ").append(contactemail);
        sb.append(", ").append(contactmethodid);
        sb.append(", ").append(contactposition);
        sb.append(", ").append(isupgradeprofile);
        sb.append(", ").append(isdeleteprofile);
        sb.append(", ").append(isallowuseredit);
        sb.append(", ").append(allowredirect);
        sb.append(", ").append(lastdateupdated);

        sb.append(")");
        return sb.toString();
    }
}
