/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbljobAdmindeletejobid implements Serializable {

    private static final long serialVersionUID = 249954215;

    private Integer jobid;

    public TbljobAdmindeletejobid() {}

    public TbljobAdmindeletejobid(TbljobAdmindeletejobid value) {
        this.jobid = value.jobid;
    }

    public TbljobAdmindeletejobid(
        Integer jobid
    ) {
        this.jobid = jobid;
    }

    public Integer getJobid() {
        return this.jobid;
    }

    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbljobAdmindeletejobid (");

        sb.append(jobid);

        sb.append(")");
        return sb.toString();
    }
}
