/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbljobAdstracking implements Serializable {

    private static final long serialVersionUID = 2145336538;

    private Integer jobid;
    private Integer topjobBannerid;
    private Integer searchresultBannerid;

    public TbljobAdstracking() {}

    public TbljobAdstracking(TbljobAdstracking value) {
        this.jobid = value.jobid;
        this.topjobBannerid = value.topjobBannerid;
        this.searchresultBannerid = value.searchresultBannerid;
    }

    public TbljobAdstracking(
        Integer jobid,
        Integer topjobBannerid,
        Integer searchresultBannerid
    ) {
        this.jobid = jobid;
        this.topjobBannerid = topjobBannerid;
        this.searchresultBannerid = searchresultBannerid;
    }

    public Integer getJobid() {
        return this.jobid;
    }

    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    public Integer getTopjobBannerid() {
        return this.topjobBannerid;
    }

    public void setTopjobBannerid(Integer topjobBannerid) {
        this.topjobBannerid = topjobBannerid;
    }

    public Integer getSearchresultBannerid() {
        return this.searchresultBannerid;
    }

    public void setSearchresultBannerid(Integer searchresultBannerid) {
        this.searchresultBannerid = searchresultBannerid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbljobAdstracking (");

        sb.append(jobid);
        sb.append(", ").append(topjobBannerid);
        sb.append(", ").append(searchresultBannerid);

        sb.append(")");
        return sb.toString();
    }
}
