/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbljobExtraprioritySchedule implements Serializable {

    private static final long serialVersionUID = -2077720663;

    private Integer   scheduleid;
    private Integer   jobid;
    private Short     industryid;
    private Timestamp createddate;
    private Timestamp expireddate;
    private Byte      duration;
    private Byte      isactive;
    private Byte      inactive;
    private Byte      isdelete;

    public TbljobExtraprioritySchedule() {}

    public TbljobExtraprioritySchedule(TbljobExtraprioritySchedule value) {
        this.scheduleid = value.scheduleid;
        this.jobid = value.jobid;
        this.industryid = value.industryid;
        this.createddate = value.createddate;
        this.expireddate = value.expireddate;
        this.duration = value.duration;
        this.isactive = value.isactive;
        this.inactive = value.inactive;
        this.isdelete = value.isdelete;
    }

    public TbljobExtraprioritySchedule(
        Integer   scheduleid,
        Integer   jobid,
        Short     industryid,
        Timestamp createddate,
        Timestamp expireddate,
        Byte      duration,
        Byte      isactive,
        Byte      inactive,
        Byte      isdelete
    ) {
        this.scheduleid = scheduleid;
        this.jobid = jobid;
        this.industryid = industryid;
        this.createddate = createddate;
        this.expireddate = expireddate;
        this.duration = duration;
        this.isactive = isactive;
        this.inactive = inactive;
        this.isdelete = isdelete;
    }

    public Integer getScheduleid() {
        return this.scheduleid;
    }

    public void setScheduleid(Integer scheduleid) {
        this.scheduleid = scheduleid;
    }

    public Integer getJobid() {
        return this.jobid;
    }

    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    public Short getIndustryid() {
        return this.industryid;
    }

    public void setIndustryid(Short industryid) {
        this.industryid = industryid;
    }

    public Timestamp getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Timestamp createddate) {
        this.createddate = createddate;
    }

    public Timestamp getExpireddate() {
        return this.expireddate;
    }

    public void setExpireddate(Timestamp expireddate) {
        this.expireddate = expireddate;
    }

    public Byte getDuration() {
        return this.duration;
    }

    public void setDuration(Byte duration) {
        this.duration = duration;
    }

    public Byte getIsactive() {
        return this.isactive;
    }

    public void setIsactive(Byte isactive) {
        this.isactive = isactive;
    }

    public Byte getInactive() {
        return this.inactive;
    }

    public void setInactive(Byte inactive) {
        this.inactive = inactive;
    }

    public Byte getIsdelete() {
        return this.isdelete;
    }

    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbljobExtraprioritySchedule (");

        sb.append(scheduleid);
        sb.append(", ").append(jobid);
        sb.append(", ").append(industryid);
        sb.append(", ").append(createddate);
        sb.append(", ").append(expireddate);
        sb.append(", ").append(duration);
        sb.append(", ").append(isactive);
        sb.append(", ").append(inactive);
        sb.append(", ").append(isdelete);

        sb.append(")");
        return sb.toString();
    }
}
