/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblNewsletterReminder implements Serializable {

    private static final long serialVersionUID = -161804220;

    private UInteger  id;
    private String    email;
    private Byte      isaddnewletter;
    private Timestamp createdate;

    public TblNewsletterReminder() {}

    public TblNewsletterReminder(TblNewsletterReminder value) {
        this.id = value.id;
        this.email = value.email;
        this.isaddnewletter = value.isaddnewletter;
        this.createdate = value.createdate;
    }

    public TblNewsletterReminder(
        UInteger  id,
        String    email,
        Byte      isaddnewletter,
        Timestamp createdate
    ) {
        this.id = id;
        this.email = email;
        this.isaddnewletter = isaddnewletter;
        this.createdate = createdate;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Byte getIsaddnewletter() {
        return this.isaddnewletter;
    }

    public void setIsaddnewletter(Byte isaddnewletter) {
        this.isaddnewletter = isaddnewletter;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblNewsletterReminder (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(isaddnewletter);
        sb.append(", ").append(createdate);

        sb.append(")");
        return sb.toString();
    }
}
