/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblproductPromotion implements Serializable {

    private static final long serialVersionUID = 140077991;

    private UInteger productpromotionId;
    private UInteger procategoryId;
    private UInteger productId;
    private Integer  productpromotionTotalcvs;

    public TblproductPromotion() {}

    public TblproductPromotion(TblproductPromotion value) {
        this.productpromotionId = value.productpromotionId;
        this.procategoryId = value.procategoryId;
        this.productId = value.productId;
        this.productpromotionTotalcvs = value.productpromotionTotalcvs;
    }

    public TblproductPromotion(
        UInteger productpromotionId,
        UInteger procategoryId,
        UInteger productId,
        Integer  productpromotionTotalcvs
    ) {
        this.productpromotionId = productpromotionId;
        this.procategoryId = procategoryId;
        this.productId = productId;
        this.productpromotionTotalcvs = productpromotionTotalcvs;
    }

    public UInteger getProductpromotionId() {
        return this.productpromotionId;
    }

    public void setProductpromotionId(UInteger productpromotionId) {
        this.productpromotionId = productpromotionId;
    }

    public UInteger getProcategoryId() {
        return this.procategoryId;
    }

    public void setProcategoryId(UInteger procategoryId) {
        this.procategoryId = procategoryId;
    }

    public UInteger getProductId() {
        return this.productId;
    }

    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    public Integer getProductpromotionTotalcvs() {
        return this.productpromotionTotalcvs;
    }

    public void setProductpromotionTotalcvs(Integer productpromotionTotalcvs) {
        this.productpromotionTotalcvs = productpromotionTotalcvs;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblproductPromotion (");

        sb.append(productpromotionId);
        sb.append(", ").append(procategoryId);
        sb.append(", ").append(productId);
        sb.append(", ").append(productpromotionTotalcvs);

        sb.append(")");
        return sb.toString();
    }
}
