/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefExtravisibility implements Serializable {

    private static final long serialVersionUID = -1134949136;

    private Byte   extravisibilityid;
    private Byte   languageid;
    private String extravisibilityname;
    private Byte   extravisibilityorder;

    public TblrefExtravisibility() {}

    public TblrefExtravisibility(TblrefExtravisibility value) {
        this.extravisibilityid = value.extravisibilityid;
        this.languageid = value.languageid;
        this.extravisibilityname = value.extravisibilityname;
        this.extravisibilityorder = value.extravisibilityorder;
    }

    public TblrefExtravisibility(
        Byte   extravisibilityid,
        Byte   languageid,
        String extravisibilityname,
        Byte   extravisibilityorder
    ) {
        this.extravisibilityid = extravisibilityid;
        this.languageid = languageid;
        this.extravisibilityname = extravisibilityname;
        this.extravisibilityorder = extravisibilityorder;
    }

    public Byte getExtravisibilityid() {
        return this.extravisibilityid;
    }

    public void setExtravisibilityid(Byte extravisibilityid) {
        this.extravisibilityid = extravisibilityid;
    }

    public Byte getLanguageid() {
        return this.languageid;
    }

    public void setLanguageid(Byte languageid) {
        this.languageid = languageid;
    }

    public String getExtravisibilityname() {
        return this.extravisibilityname;
    }

    public void setExtravisibilityname(String extravisibilityname) {
        this.extravisibilityname = extravisibilityname;
    }

    public Byte getExtravisibilityorder() {
        return this.extravisibilityorder;
    }

    public void setExtravisibilityorder(Byte extravisibilityorder) {
        this.extravisibilityorder = extravisibilityorder;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblrefExtravisibility (");

        sb.append(extravisibilityid);
        sb.append(", ").append(languageid);
        sb.append(", ").append(extravisibilityname);
        sb.append(", ").append(extravisibilityorder);

        sb.append(")");
        return sb.toString();
    }
}
