/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefJoblevel implements Serializable {

    private static final long serialVersionUID = 1575713023;

    private Byte   joblevelid;
    private Byte   languageid;
    private String joblevelname;
    private Byte   joblevelorder;

    public TblrefJoblevel() {}

    public TblrefJoblevel(TblrefJoblevel value) {
        this.joblevelid = value.joblevelid;
        this.languageid = value.languageid;
        this.joblevelname = value.joblevelname;
        this.joblevelorder = value.joblevelorder;
    }

    public TblrefJoblevel(
        Byte   joblevelid,
        Byte   languageid,
        String joblevelname,
        Byte   joblevelorder
    ) {
        this.joblevelid = joblevelid;
        this.languageid = languageid;
        this.joblevelname = joblevelname;
        this.joblevelorder = joblevelorder;
    }

    public Byte getJoblevelid() {
        return this.joblevelid;
    }

    public void setJoblevelid(Byte joblevelid) {
        this.joblevelid = joblevelid;
    }

    public Byte getLanguageid() {
        return this.languageid;
    }

    public void setLanguageid(Byte languageid) {
        this.languageid = languageid;
    }

    public String getJoblevelname() {
        return this.joblevelname;
    }

    public void setJoblevelname(String joblevelname) {
        this.joblevelname = joblevelname;
    }

    public Byte getJoblevelorder() {
        return this.joblevelorder;
    }

    public void setJoblevelorder(Byte joblevelorder) {
        this.joblevelorder = joblevelorder;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblrefJoblevel (");

        sb.append(joblevelid);
        sb.append(", ").append(languageid);
        sb.append(", ").append(joblevelname);
        sb.append(", ").append(joblevelorder);

        sb.append(")");
        return sb.toString();
    }
}
