/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefServicedescription implements Serializable {

    private static final long serialVersionUID = 840806009;

    private Integer serviceId;
    private Short   languageid;
    private String  servicedescName;
    private String  servicedescDescription;

    public TblrefServicedescription() {}

    public TblrefServicedescription(TblrefServicedescription value) {
        this.serviceId = value.serviceId;
        this.languageid = value.languageid;
        this.servicedescName = value.servicedescName;
        this.servicedescDescription = value.servicedescDescription;
    }

    public TblrefServicedescription(
        Integer serviceId,
        Short   languageid,
        String  servicedescName,
        String  servicedescDescription
    ) {
        this.serviceId = serviceId;
        this.languageid = languageid;
        this.servicedescName = servicedescName;
        this.servicedescDescription = servicedescDescription;
    }

    public Integer getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    public Short getLanguageid() {
        return this.languageid;
    }

    public void setLanguageid(Short languageid) {
        this.languageid = languageid;
    }

    public String getServicedescName() {
        return this.servicedescName;
    }

    public void setServicedescName(String servicedescName) {
        this.servicedescName = servicedescName;
    }

    public String getServicedescDescription() {
        return this.servicedescDescription;
    }

    public void setServicedescDescription(String servicedescDescription) {
        this.servicedescDescription = servicedescDescription;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblrefServicedescription (");

        sb.append(serviceId);
        sb.append(", ").append(languageid);
        sb.append(", ").append(servicedescName);
        sb.append(", ").append(servicedescDescription);

        sb.append(")");
        return sb.toString();
    }
}
