/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblresumeDeny implements Serializable {

    private static final long serialVersionUID = -140654015;

    private UInteger  id;
    private UInteger  resumeid;
    private String    reasondeny;
    private Timestamp datedeny;

    public TblresumeDeny() {}

    public TblresumeDeny(TblresumeDeny value) {
        this.id = value.id;
        this.resumeid = value.resumeid;
        this.reasondeny = value.reasondeny;
        this.datedeny = value.datedeny;
    }

    public TblresumeDeny(
        UInteger  id,
        UInteger  resumeid,
        String    reasondeny,
        Timestamp datedeny
    ) {
        this.id = id;
        this.resumeid = resumeid;
        this.reasondeny = reasondeny;
        this.datedeny = datedeny;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UInteger getResumeid() {
        return this.resumeid;
    }

    public void setResumeid(UInteger resumeid) {
        this.resumeid = resumeid;
    }

    public String getReasondeny() {
        return this.reasondeny;
    }

    public void setReasondeny(String reasondeny) {
        this.reasondeny = reasondeny;
    }

    public Timestamp getDatedeny() {
        return this.datedeny;
    }

    public void setDatedeny(Timestamp datedeny) {
        this.datedeny = datedeny;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblresumeDeny (");

        sb.append(id);
        sb.append(", ").append(resumeid);
        sb.append(", ").append(reasondeny);
        sb.append(", ").append(datedeny);

        sb.append(")");
        return sb.toString();
    }
}
