/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefNationalitycode implements Serializable {

    private static final long serialVersionUID = 596420601;

    private Byte   nationalityid;
    private String nationalitycode;

    public TblrefNationalitycode() {}

    public TblrefNationalitycode(TblrefNationalitycode value) {
        this.nationalityid = value.nationalityid;
        this.nationalitycode = value.nationalitycode;
    }

    public TblrefNationalitycode(
        Byte   nationalityid,
        String nationalitycode
    ) {
        this.nationalityid = nationalityid;
        this.nationalitycode = nationalitycode;
    }

    public Byte getNationalityid() {
        return this.nationalityid;
    }

    public void setNationalityid(Byte nationalityid) {
        this.nationalityid = nationalityid;
    }

    public String getNationalitycode() {
        return this.nationalitycode;
    }

    public void setNationalitycode(String nationalitycode) {
        this.nationalitycode = nationalitycode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblrefNationalitycode (");

        sb.append(nationalityid);
        sb.append(", ").append(nationalitycode);

        sb.append(")");
        return sb.toString();
    }
}
