/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblresumeViewingOrder implements Serializable {

    private static final long serialVersionUID = 578384803;

    private Integer   orderid;
    private Integer   userid;
    private Byte      languageid;
    private Byte      resumeviewingoptionid;
    private Integer   billingcontactid;
    private Double    paymentfee;
    private Integer   cvBought;
    private Integer   cvPromotion;
    private Integer   cvRemaining;
    private Timestamp registereddate;
    private Timestamp activedate;
    private Short     durationdays;
    private Timestamp expireddate;
    private Byte      ispaid;
    private Byte      islocked;
    private Byte      islockedby;
    private Integer   productId;

    public TblresumeViewingOrder() {}

    public TblresumeViewingOrder(TblresumeViewingOrder value) {
        this.orderid = value.orderid;
        this.userid = value.userid;
        this.languageid = value.languageid;
        this.resumeviewingoptionid = value.resumeviewingoptionid;
        this.billingcontactid = value.billingcontactid;
        this.paymentfee = value.paymentfee;
        this.cvBought = value.cvBought;
        this.cvPromotion = value.cvPromotion;
        this.cvRemaining = value.cvRemaining;
        this.registereddate = value.registereddate;
        this.activedate = value.activedate;
        this.durationdays = value.durationdays;
        this.expireddate = value.expireddate;
        this.ispaid = value.ispaid;
        this.islocked = value.islocked;
        this.islockedby = value.islockedby;
        this.productId = value.productId;
    }

    public TblresumeViewingOrder(
        Integer   orderid,
        Integer   userid,
        Byte      languageid,
        Byte      resumeviewingoptionid,
        Integer   billingcontactid,
        Double    paymentfee,
        Integer   cvBought,
        Integer   cvPromotion,
        Integer   cvRemaining,
        Timestamp registereddate,
        Timestamp activedate,
        Short     durationdays,
        Timestamp expireddate,
        Byte      ispaid,
        Byte      islocked,
        Byte      islockedby,
        Integer   productId
    ) {
        this.orderid = orderid;
        this.userid = userid;
        this.languageid = languageid;
        this.resumeviewingoptionid = resumeviewingoptionid;
        this.billingcontactid = billingcontactid;
        this.paymentfee = paymentfee;
        this.cvBought = cvBought;
        this.cvPromotion = cvPromotion;
        this.cvRemaining = cvRemaining;
        this.registereddate = registereddate;
        this.activedate = activedate;
        this.durationdays = durationdays;
        this.expireddate = expireddate;
        this.ispaid = ispaid;
        this.islocked = islocked;
        this.islockedby = islockedby;
        this.productId = productId;
    }

    public Integer getOrderid() {
        return this.orderid;
    }

    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Byte getLanguageid() {
        return this.languageid;
    }

    public void setLanguageid(Byte languageid) {
        this.languageid = languageid;
    }

    public Byte getResumeviewingoptionid() {
        return this.resumeviewingoptionid;
    }

    public void setResumeviewingoptionid(Byte resumeviewingoptionid) {
        this.resumeviewingoptionid = resumeviewingoptionid;
    }

    public Integer getBillingcontactid() {
        return this.billingcontactid;
    }

    public void setBillingcontactid(Integer billingcontactid) {
        this.billingcontactid = billingcontactid;
    }

    public Double getPaymentfee() {
        return this.paymentfee;
    }

    public void setPaymentfee(Double paymentfee) {
        this.paymentfee = paymentfee;
    }

    public Integer getCvBought() {
        return this.cvBought;
    }

    public void setCvBought(Integer cvBought) {
        this.cvBought = cvBought;
    }

    public Integer getCvPromotion() {
        return this.cvPromotion;
    }

    public void setCvPromotion(Integer cvPromotion) {
        this.cvPromotion = cvPromotion;
    }

    public Integer getCvRemaining() {
        return this.cvRemaining;
    }

    public void setCvRemaining(Integer cvRemaining) {
        this.cvRemaining = cvRemaining;
    }

    public Timestamp getRegistereddate() {
        return this.registereddate;
    }

    public void setRegistereddate(Timestamp registereddate) {
        this.registereddate = registereddate;
    }

    public Timestamp getActivedate() {
        return this.activedate;
    }

    public void setActivedate(Timestamp activedate) {
        this.activedate = activedate;
    }

    public Short getDurationdays() {
        return this.durationdays;
    }

    public void setDurationdays(Short durationdays) {
        this.durationdays = durationdays;
    }

    public Timestamp getExpireddate() {
        return this.expireddate;
    }

    public void setExpireddate(Timestamp expireddate) {
        this.expireddate = expireddate;
    }

    public Byte getIspaid() {
        return this.ispaid;
    }

    public void setIspaid(Byte ispaid) {
        this.ispaid = ispaid;
    }

    public Byte getIslocked() {
        return this.islocked;
    }

    public void setIslocked(Byte islocked) {
        this.islocked = islocked;
    }

    public Byte getIslockedby() {
        return this.islockedby;
    }

    public void setIslockedby(Byte islockedby) {
        this.islockedby = islockedby;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblresumeViewingOrder (");

        sb.append(orderid);
        sb.append(", ").append(userid);
        sb.append(", ").append(languageid);
        sb.append(", ").append(resumeviewingoptionid);
        sb.append(", ").append(billingcontactid);
        sb.append(", ").append(paymentfee);
        sb.append(", ").append(cvBought);
        sb.append(", ").append(cvPromotion);
        sb.append(", ").append(cvRemaining);
        sb.append(", ").append(registereddate);
        sb.append(", ").append(activedate);
        sb.append(", ").append(durationdays);
        sb.append(", ").append(expireddate);
        sb.append(", ").append(ispaid);
        sb.append(", ").append(islocked);
        sb.append(", ").append(islockedby);
        sb.append(", ").append(productId);

        sb.append(")");
        return sb.toString();
    }
}
