/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefSchoolcode implements Serializable {

    private static final long serialVersionUID = -755711914;

    private Short  schoolid;
    private String schoolcode;
    private Byte   regionid;

    public TblrefSchoolcode() {}

    public TblrefSchoolcode(TblrefSchoolcode value) {
        this.schoolid = value.schoolid;
        this.schoolcode = value.schoolcode;
        this.regionid = value.regionid;
    }

    public TblrefSchoolcode(
        Short  schoolid,
        String schoolcode,
        Byte   regionid
    ) {
        this.schoolid = schoolid;
        this.schoolcode = schoolcode;
        this.regionid = regionid;
    }

    public Short getSchoolid() {
        return this.schoolid;
    }

    public void setSchoolid(Short schoolid) {
        this.schoolid = schoolid;
    }

    public String getSchoolcode() {
        return this.schoolcode;
    }

    public void setSchoolcode(String schoolcode) {
        this.schoolcode = schoolcode;
    }

    public Byte getRegionid() {
        return this.regionid;
    }

    public void setRegionid(Byte regionid) {
        this.regionid = regionid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblrefSchoolcode (");

        sb.append(schoolid);
        sb.append(", ").append(schoolcode);
        sb.append(", ").append(regionid);

        sb.append(")");
        return sb.toString();
    }
}
