/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Count resume that intermship upgraded
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblresumeUpgradingByuser implements Serializable {

    private static final long serialVersionUID = 40871156;

    private Integer   userid;
    private Integer   resumeid;
    private Timestamp dateupgraded;

    public TblresumeUpgradingByuser() {}

    public TblresumeUpgradingByuser(TblresumeUpgradingByuser value) {
        this.userid = value.userid;
        this.resumeid = value.resumeid;
        this.dateupgraded = value.dateupgraded;
    }

    public TblresumeUpgradingByuser(
        Integer   userid,
        Integer   resumeid,
        Timestamp dateupgraded
    ) {
        this.userid = userid;
        this.resumeid = resumeid;
        this.dateupgraded = dateupgraded;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getResumeid() {
        return this.resumeid;
    }

    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    public Timestamp getDateupgraded() {
        return this.dateupgraded;
    }

    public void setDateupgraded(Timestamp dateupgraded) {
        this.dateupgraded = dateupgraded;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblresumeUpgradingByuser (");

        sb.append(userid);
        sb.append(", ").append(resumeid);
        sb.append(", ").append(dateupgraded);

        sb.append(")");
        return sb.toString();
    }
}
