/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefCountrycode implements Serializable {

    private static final long serialVersionUID = -852746375;

    private Short  countryid;
    private String countrycode;

    public TblrefCountrycode() {}

    public TblrefCountrycode(TblrefCountrycode value) {
        this.countryid = value.countryid;
        this.countrycode = value.countrycode;
    }

    public TblrefCountrycode(
        Short  countryid,
        String countrycode
    ) {
        this.countryid = countryid;
        this.countrycode = countrycode;
    }

    public Short getCountryid() {
        return this.countryid;
    }

    public void setCountryid(Short countryid) {
        this.countryid = countryid;
    }

    public String getCountrycode() {
        return this.countrycode;
    }

    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblrefCountrycode (");

        sb.append(countryid);
        sb.append(", ").append(countrycode);

        sb.append(")");
        return sb.toString();
    }
}
