/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblscreenTest implements Serializable {

    private static final long serialVersionUID = 396648573;

    private UInteger  testid;
    private UInteger  oritestid;
    private UInteger  userid;
    private Byte      testtype;
    private String    name;
    private UByte     noofquestion;
    private Timestamp createddate;
    private Timestamp lastupdateddate;
    private Byte      isdeleted;
    private Byte      iscompleted;
    private Byte      isactive;

    public TblscreenTest() {}

    public TblscreenTest(TblscreenTest value) {
        this.testid = value.testid;
        this.oritestid = value.oritestid;
        this.userid = value.userid;
        this.testtype = value.testtype;
        this.name = value.name;
        this.noofquestion = value.noofquestion;
        this.createddate = value.createddate;
        this.lastupdateddate = value.lastupdateddate;
        this.isdeleted = value.isdeleted;
        this.iscompleted = value.iscompleted;
        this.isactive = value.isactive;
    }

    public TblscreenTest(
        UInteger  testid,
        UInteger  oritestid,
        UInteger  userid,
        Byte      testtype,
        String    name,
        UByte     noofquestion,
        Timestamp createddate,
        Timestamp lastupdateddate,
        Byte      isdeleted,
        Byte      iscompleted,
        Byte      isactive
    ) {
        this.testid = testid;
        this.oritestid = oritestid;
        this.userid = userid;
        this.testtype = testtype;
        this.name = name;
        this.noofquestion = noofquestion;
        this.createddate = createddate;
        this.lastupdateddate = lastupdateddate;
        this.isdeleted = isdeleted;
        this.iscompleted = iscompleted;
        this.isactive = isactive;
    }

    public UInteger getTestid() {
        return this.testid;
    }

    public void setTestid(UInteger testid) {
        this.testid = testid;
    }

    public UInteger getOritestid() {
        return this.oritestid;
    }

    public void setOritestid(UInteger oritestid) {
        this.oritestid = oritestid;
    }

    public UInteger getUserid() {
        return this.userid;
    }

    public void setUserid(UInteger userid) {
        this.userid = userid;
    }

    public Byte getTesttype() {
        return this.testtype;
    }

    public void setTesttype(Byte testtype) {
        this.testtype = testtype;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UByte getNoofquestion() {
        return this.noofquestion;
    }

    public void setNoofquestion(UByte noofquestion) {
        this.noofquestion = noofquestion;
    }

    public Timestamp getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Timestamp createddate) {
        this.createddate = createddate;
    }

    public Timestamp getLastupdateddate() {
        return this.lastupdateddate;
    }

    public void setLastupdateddate(Timestamp lastupdateddate) {
        this.lastupdateddate = lastupdateddate;
    }

    public Byte getIsdeleted() {
        return this.isdeleted;
    }

    public void setIsdeleted(Byte isdeleted) {
        this.isdeleted = isdeleted;
    }

    public Byte getIscompleted() {
        return this.iscompleted;
    }

    public void setIscompleted(Byte iscompleted) {
        this.iscompleted = iscompleted;
    }

    public Byte getIsactive() {
        return this.isactive;
    }

    public void setIsactive(Byte isactive) {
        this.isactive = isactive;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblscreenTest (");

        sb.append(testid);
        sb.append(", ").append(oritestid);
        sb.append(", ").append(userid);
        sb.append(", ").append(testtype);
        sb.append(", ").append(name);
        sb.append(", ").append(noofquestion);
        sb.append(", ").append(createddate);
        sb.append(", ").append(lastupdateddate);
        sb.append(", ").append(isdeleted);
        sb.append(", ").append(iscompleted);
        sb.append(", ").append(isactive);

        sb.append(")");
        return sb.toString();
    }
}
