/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblscreenTestOption implements Serializable {

    private static final long serialVersionUID = 1589804525;

    private UInteger testid;
    private UInteger questionid;
    private UByte    optionid;
    private Byte     optionorder;
    private String   content;

    public TblscreenTestOption() {}

    public TblscreenTestOption(TblscreenTestOption value) {
        this.testid = value.testid;
        this.questionid = value.questionid;
        this.optionid = value.optionid;
        this.optionorder = value.optionorder;
        this.content = value.content;
    }

    public TblscreenTestOption(
        UInteger testid,
        UInteger questionid,
        UByte    optionid,
        Byte     optionorder,
        String   content
    ) {
        this.testid = testid;
        this.questionid = questionid;
        this.optionid = optionid;
        this.optionorder = optionorder;
        this.content = content;
    }

    public UInteger getTestid() {
        return this.testid;
    }

    public void setTestid(UInteger testid) {
        this.testid = testid;
    }

    public UInteger getQuestionid() {
        return this.questionid;
    }

    public void setQuestionid(UInteger questionid) {
        this.questionid = questionid;
    }

    public UByte getOptionid() {
        return this.optionid;
    }

    public void setOptionid(UByte optionid) {
        this.optionid = optionid;
    }

    public Byte getOptionorder() {
        return this.optionorder;
    }

    public void setOptionorder(Byte optionorder) {
        this.optionorder = optionorder;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblscreenTestOption (");

        sb.append(testid);
        sb.append(", ").append(questionid);
        sb.append(", ").append(optionid);
        sb.append(", ").append(optionorder);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
