/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbltrackSalesEmployer implements Serializable {

    private static final long serialVersionUID = -142006661;

    private UInteger  trackid;
    private UInteger  userid;
    private UInteger  employerid;
    private UInteger  jobid;
    private String    action;
    private Timestamp datetime;

    public TbltrackSalesEmployer() {}

    public TbltrackSalesEmployer(TbltrackSalesEmployer value) {
        this.trackid = value.trackid;
        this.userid = value.userid;
        this.employerid = value.employerid;
        this.jobid = value.jobid;
        this.action = value.action;
        this.datetime = value.datetime;
    }

    public TbltrackSalesEmployer(
        UInteger  trackid,
        UInteger  userid,
        UInteger  employerid,
        UInteger  jobid,
        String    action,
        Timestamp datetime
    ) {
        this.trackid = trackid;
        this.userid = userid;
        this.employerid = employerid;
        this.jobid = jobid;
        this.action = action;
        this.datetime = datetime;
    }

    public UInteger getTrackid() {
        return this.trackid;
    }

    public void setTrackid(UInteger trackid) {
        this.trackid = trackid;
    }

    public UInteger getUserid() {
        return this.userid;
    }

    public void setUserid(UInteger userid) {
        this.userid = userid;
    }

    public UInteger getEmployerid() {
        return this.employerid;
    }

    public void setEmployerid(UInteger employerid) {
        this.employerid = employerid;
    }

    public UInteger getJobid() {
        return this.jobid;
    }

    public void setJobid(UInteger jobid) {
        this.jobid = jobid;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public Timestamp getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Timestamp datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbltrackSalesEmployer (");

        sb.append(trackid);
        sb.append(", ").append(userid);
        sb.append(", ").append(employerid);
        sb.append(", ").append(jobid);
        sb.append(", ").append(action);
        sb.append(", ").append(datetime);

        sb.append(")");
        return sb.toString();
    }
}
