/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbltrackSpecialOffers implements Serializable {

    private static final long serialVersionUID = 1618459429;

    private String    email;
    private Timestamp createddate;
    private String    clientip;

    public TbltrackSpecialOffers() {}

    public TbltrackSpecialOffers(TbltrackSpecialOffers value) {
        this.email = value.email;
        this.createddate = value.createddate;
        this.clientip = value.clientip;
    }

    public TbltrackSpecialOffers(
        String    email,
        Timestamp createddate,
        String    clientip
    ) {
        this.email = email;
        this.createddate = createddate;
        this.clientip = clientip;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Timestamp getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Timestamp createddate) {
        this.createddate = createddate;
    }

    public String getClientip() {
        return this.clientip;
    }

    public void setClientip(String clientip) {
        this.clientip = clientip;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbltrackSpecialOffers (");

        sb.append(email);
        sb.append(", ").append(createddate);
        sb.append(", ").append(clientip);

        sb.append(")");
        return sb.toString();
    }
}
