/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbluserSuspended implements Serializable {

    private static final long serialVersionUID = -1437938923;

    private UInteger  entryid;
    private UInteger  userid;
    private Timestamp suspendedDate;
    private Timestamp suspendedTo;
    private Byte      isBanned;
    private Byte      ruleId;

    public TbluserSuspended() {}

    public TbluserSuspended(TbluserSuspended value) {
        this.entryid = value.entryid;
        this.userid = value.userid;
        this.suspendedDate = value.suspendedDate;
        this.suspendedTo = value.suspendedTo;
        this.isBanned = value.isBanned;
        this.ruleId = value.ruleId;
    }

    public TbluserSuspended(
        UInteger  entryid,
        UInteger  userid,
        Timestamp suspendedDate,
        Timestamp suspendedTo,
        Byte      isBanned,
        Byte      ruleId
    ) {
        this.entryid = entryid;
        this.userid = userid;
        this.suspendedDate = suspendedDate;
        this.suspendedTo = suspendedTo;
        this.isBanned = isBanned;
        this.ruleId = ruleId;
    }

    public UInteger getEntryid() {
        return this.entryid;
    }

    public void setEntryid(UInteger entryid) {
        this.entryid = entryid;
    }

    public UInteger getUserid() {
        return this.userid;
    }

    public void setUserid(UInteger userid) {
        this.userid = userid;
    }

    public Timestamp getSuspendedDate() {
        return this.suspendedDate;
    }

    public void setSuspendedDate(Timestamp suspendedDate) {
        this.suspendedDate = suspendedDate;
    }

    public Timestamp getSuspendedTo() {
        return this.suspendedTo;
    }

    public void setSuspendedTo(Timestamp suspendedTo) {
        this.suspendedTo = suspendedTo;
    }

    public Byte getIsBanned() {
        return this.isBanned;
    }

    public void setIsBanned(Byte isBanned) {
        this.isBanned = isBanned;
    }

    public Byte getRuleId() {
        return this.ruleId;
    }

    public void setRuleId(Byte ruleId) {
        this.ruleId = ruleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbluserSuspended (");

        sb.append(entryid);
        sb.append(", ").append(userid);
        sb.append(", ").append(suspendedDate);
        sb.append(", ").append(suspendedTo);
        sb.append(", ").append(isBanned);
        sb.append(", ").append(ruleId);

        sb.append(")");
        return sb.toString();
    }
}
