/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblwsRegistration implements Serializable {

    private static final long serialVersionUID = -2087079217;

    private Integer   entryid;
    private String    fullname;
    private Timestamp birthday;
    private String    email;
    private String    phonenumber;
    private String    mostrecentposition;
    private Timestamp createddate;

    public TblwsRegistration() {}

    public TblwsRegistration(TblwsRegistration value) {
        this.entryid = value.entryid;
        this.fullname = value.fullname;
        this.birthday = value.birthday;
        this.email = value.email;
        this.phonenumber = value.phonenumber;
        this.mostrecentposition = value.mostrecentposition;
        this.createddate = value.createddate;
    }

    public TblwsRegistration(
        Integer   entryid,
        String    fullname,
        Timestamp birthday,
        String    email,
        String    phonenumber,
        String    mostrecentposition,
        Timestamp createddate
    ) {
        this.entryid = entryid;
        this.fullname = fullname;
        this.birthday = birthday;
        this.email = email;
        this.phonenumber = phonenumber;
        this.mostrecentposition = mostrecentposition;
        this.createddate = createddate;
    }

    public Integer getEntryid() {
        return this.entryid;
    }

    public void setEntryid(Integer entryid) {
        this.entryid = entryid;
    }

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public Timestamp getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Timestamp birthday) {
        this.birthday = birthday;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhonenumber() {
        return this.phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public String getMostrecentposition() {
        return this.mostrecentposition;
    }

    public void setMostrecentposition(String mostrecentposition) {
        this.mostrecentposition = mostrecentposition;
    }

    public Timestamp getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Timestamp createddate) {
        this.createddate = createddate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TblwsRegistration (");

        sb.append(entryid);
        sb.append(", ").append(fullname);
        sb.append(", ").append(birthday);
        sb.append(", ").append(email);
        sb.append(", ").append(phonenumber);
        sb.append(", ").append(mostrecentposition);
        sb.append(", ").append(createddate);

        sb.append(")");
        return sb.toString();
    }
}
