/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackJobUpdate implements Serializable {

    private static final long serialVersionUID = -1422231804;

    private ULong     id;
    private UInteger  jobId;
    private UInteger  userId;
    private String    title;
    private String    description;
    private String    emailContact;
    private Integer   salaryrangeId;
    private Integer   salaryMin;
    private Integer   saralyMax;
    private UByte     industry1Id;
    private UByte     industry1VisibilityId;
    private UByte     industry1PriorityId;
    private UByte     industry2Id;
    private UByte     industry2VisibilityId;
    private UByte     industry2PriorityId;
    private UByte     industry3Id;
    private UByte     industry3VisibilityId;
    private UByte     industry3PriorityId;
    private UByte     isOnHomepage;
    private Timestamp createAt;

    public TrackJobUpdate() {}

    public TrackJobUpdate(TrackJobUpdate value) {
        this.id = value.id;
        this.jobId = value.jobId;
        this.userId = value.userId;
        this.title = value.title;
        this.description = value.description;
        this.emailContact = value.emailContact;
        this.salaryrangeId = value.salaryrangeId;
        this.salaryMin = value.salaryMin;
        this.saralyMax = value.saralyMax;
        this.industry1Id = value.industry1Id;
        this.industry1VisibilityId = value.industry1VisibilityId;
        this.industry1PriorityId = value.industry1PriorityId;
        this.industry2Id = value.industry2Id;
        this.industry2VisibilityId = value.industry2VisibilityId;
        this.industry2PriorityId = value.industry2PriorityId;
        this.industry3Id = value.industry3Id;
        this.industry3VisibilityId = value.industry3VisibilityId;
        this.industry3PriorityId = value.industry3PriorityId;
        this.isOnHomepage = value.isOnHomepage;
        this.createAt = value.createAt;
    }

    public TrackJobUpdate(
        ULong     id,
        UInteger  jobId,
        UInteger  userId,
        String    title,
        String    description,
        String    emailContact,
        Integer   salaryrangeId,
        Integer   salaryMin,
        Integer   saralyMax,
        UByte     industry1Id,
        UByte     industry1VisibilityId,
        UByte     industry1PriorityId,
        UByte     industry2Id,
        UByte     industry2VisibilityId,
        UByte     industry2PriorityId,
        UByte     industry3Id,
        UByte     industry3VisibilityId,
        UByte     industry3PriorityId,
        UByte     isOnHomepage,
        Timestamp createAt
    ) {
        this.id = id;
        this.jobId = jobId;
        this.userId = userId;
        this.title = title;
        this.description = description;
        this.emailContact = emailContact;
        this.salaryrangeId = salaryrangeId;
        this.salaryMin = salaryMin;
        this.saralyMax = saralyMax;
        this.industry1Id = industry1Id;
        this.industry1VisibilityId = industry1VisibilityId;
        this.industry1PriorityId = industry1PriorityId;
        this.industry2Id = industry2Id;
        this.industry2VisibilityId = industry2VisibilityId;
        this.industry2PriorityId = industry2PriorityId;
        this.industry3Id = industry3Id;
        this.industry3VisibilityId = industry3VisibilityId;
        this.industry3PriorityId = industry3PriorityId;
        this.isOnHomepage = isOnHomepage;
        this.createAt = createAt;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public UInteger getJobId() {
        return this.jobId;
    }

    public void setJobId(UInteger jobId) {
        this.jobId = jobId;
    }

    public UInteger getUserId() {
        return this.userId;
    }

    public void setUserId(UInteger userId) {
        this.userId = userId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getEmailContact() {
        return this.emailContact;
    }

    public void setEmailContact(String emailContact) {
        this.emailContact = emailContact;
    }

    public Integer getSalaryrangeId() {
        return this.salaryrangeId;
    }

    public void setSalaryrangeId(Integer salaryrangeId) {
        this.salaryrangeId = salaryrangeId;
    }

    public Integer getSalaryMin() {
        return this.salaryMin;
    }

    public void setSalaryMin(Integer salaryMin) {
        this.salaryMin = salaryMin;
    }

    public Integer getSaralyMax() {
        return this.saralyMax;
    }

    public void setSaralyMax(Integer saralyMax) {
        this.saralyMax = saralyMax;
    }

    public UByte getIndustry1Id() {
        return this.industry1Id;
    }

    public void setIndustry1Id(UByte industry1Id) {
        this.industry1Id = industry1Id;
    }

    public UByte getIndustry1VisibilityId() {
        return this.industry1VisibilityId;
    }

    public void setIndustry1VisibilityId(UByte industry1VisibilityId) {
        this.industry1VisibilityId = industry1VisibilityId;
    }

    public UByte getIndustry1PriorityId() {
        return this.industry1PriorityId;
    }

    public void setIndustry1PriorityId(UByte industry1PriorityId) {
        this.industry1PriorityId = industry1PriorityId;
    }

    public UByte getIndustry2Id() {
        return this.industry2Id;
    }

    public void setIndustry2Id(UByte industry2Id) {
        this.industry2Id = industry2Id;
    }

    public UByte getIndustry2VisibilityId() {
        return this.industry2VisibilityId;
    }

    public void setIndustry2VisibilityId(UByte industry2VisibilityId) {
        this.industry2VisibilityId = industry2VisibilityId;
    }

    public UByte getIndustry2PriorityId() {
        return this.industry2PriorityId;
    }

    public void setIndustry2PriorityId(UByte industry2PriorityId) {
        this.industry2PriorityId = industry2PriorityId;
    }

    public UByte getIndustry3Id() {
        return this.industry3Id;
    }

    public void setIndustry3Id(UByte industry3Id) {
        this.industry3Id = industry3Id;
    }

    public UByte getIndustry3VisibilityId() {
        return this.industry3VisibilityId;
    }

    public void setIndustry3VisibilityId(UByte industry3VisibilityId) {
        this.industry3VisibilityId = industry3VisibilityId;
    }

    public UByte getIndustry3PriorityId() {
        return this.industry3PriorityId;
    }

    public void setIndustry3PriorityId(UByte industry3PriorityId) {
        this.industry3PriorityId = industry3PriorityId;
    }

    public UByte getIsOnHomepage() {
        return this.isOnHomepage;
    }

    public void setIsOnHomepage(UByte isOnHomepage) {
        this.isOnHomepage = isOnHomepage;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrackJobUpdate (");

        sb.append(id);
        sb.append(", ").append(jobId);
        sb.append(", ").append(userId);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(emailContact);
        sb.append(", ").append(salaryrangeId);
        sb.append(", ").append(salaryMin);
        sb.append(", ").append(saralyMax);
        sb.append(", ").append(industry1Id);
        sb.append(", ").append(industry1VisibilityId);
        sb.append(", ").append(industry1PriorityId);
        sb.append(", ").append(industry2Id);
        sb.append(", ").append(industry2VisibilityId);
        sb.append(", ").append(industry2PriorityId);
        sb.append(", ").append(industry3Id);
        sb.append(", ").append(industry3VisibilityId);
        sb.append(", ").append(industry3PriorityId);
        sb.append(", ").append(isOnHomepage);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
