/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.routines;


import com.vnw.data.jooq.VnwCore;

import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getresumeapplications extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1894614637;

    /**
     * Create a new routine call instance
     */
    public Getresumeapplications() {
        super("getResumeApplications", VnwCore.VNW_CORE);
    }
}
