/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.EtlJobViews;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtlJobViewsRecord extends UpdatableRecordImpl<EtlJobViewsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1619111157;

    /**
     * Setter for <code>vnw_core.etl_job_views.jobId</code>.
     */
    public void setJobid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.etl_job_views.jobId</code>.
     */
    public Integer getJobid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.etl_job_views.noOfViews</code>.
     */
    public void setNoofviews(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.etl_job_views.noOfViews</code>.
     */
    public Integer getNoofviews() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EtlJobViews.ETL_JOB_VIEWS.JOBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EtlJobViews.ETL_JOB_VIEWS.NOOFVIEWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getJobid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNoofviews();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtlJobViewsRecord value1(Integer value) {
        setJobid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtlJobViewsRecord value2(Integer value) {
        setNoofviews(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtlJobViewsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EtlJobViewsRecord
     */
    public EtlJobViewsRecord() {
        super(EtlJobViews.ETL_JOB_VIEWS);
    }

    /**
     * Create a detached, initialised EtlJobViewsRecord
     */
    public EtlJobViewsRecord(Integer jobid, Integer noofviews) {
        super(EtlJobViews.ETL_JOB_VIEWS);

        set(0, jobid);
        set(1, noofviews);
    }
}
