/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.Tblbillingcontact;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblbillingcontactRecord extends UpdatableRecordImpl<TblbillingcontactRecord> implements Record15<Integer, String, String, String, String, String, String, Short, Integer, String, String, String, String, String, Byte> {

    private static final long serialVersionUID = -557042898;

    /**
     * Setter for <code>vnw_core.tblbillingcontact.contactid</code>.
     */
    public void setContactid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.contactid</code>.
     */
    public Integer getContactid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.contactname</code>.
     */
    public void setContactname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.contactname</code>.
     */
    public String getContactname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.contactpersonposition</code>.
     */
    public void setContactpersonposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.contactpersonposition</code>.
     */
    public String getContactpersonposition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.companyname</code>.
     */
    public void setCompanyname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.companyname</code>.
     */
    public String getCompanyname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.taxcode</code>.
     */
    public void setTaxcode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.taxcode</code>.
     */
    public String getTaxcode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.district</code>.
     */
    public void setDistrict(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.district</code>.
     */
    public String getDistrict() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.countryid</code>.
     */
    public void setCountryid(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.countryid</code>.
     */
    public Short getCountryid() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.cityid</code>.
     */
    public void setCityid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.cityid</code>.
     */
    public Integer getCityid() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.cityname</code>.
     */
    public void setCityname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.cityname</code>.
     */
    public String getCityname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.companyphone</code>.
     */
    public void setCompanyphone(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.companyphone</code>.
     */
    public String getCompanyphone() {
        return (String) get(10);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.cellphone</code>.
     */
    public void setCellphone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.cellphone</code>.
     */
    public String getCellphone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.companyfax</code>.
     */
    public void setCompanyfax(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.companyfax</code>.
     */
    public String getCompanyfax() {
        return (String) get(12);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.contactemail</code>.
     */
    public void setContactemail(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.contactemail</code>.
     */
    public String getContactemail() {
        return (String) get(13);
    }

    /**
     * Setter for <code>vnw_core.tblbillingcontact.paymentmethodid</code>.
     */
    public void setPaymentmethodid(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>vnw_core.tblbillingcontact.paymentmethodid</code>.
     */
    public Byte getPaymentmethodid() {
        return (Byte) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, String, Short, Integer, String, String, String, String, String, Byte> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, String, Short, Integer, String, String, String, String, String, Byte> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CONTACTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CONTACTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CONTACTPERSONPOSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tblbillingcontact.TBLBILLINGCONTACT.COMPANYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Tblbillingcontact.TBLBILLINGCONTACT.TAXCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tblbillingcontact.TBLBILLINGCONTACT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Tblbillingcontact.TBLBILLINGCONTACT.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return Tblbillingcontact.TBLBILLINGCONTACT.COUNTRYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CITYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Tblbillingcontact.TBLBILLINGCONTACT.COMPANYPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CELLPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Tblbillingcontact.TBLBILLINGCONTACT.COMPANYFAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Tblbillingcontact.TBLBILLINGCONTACT.CONTACTEMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field15() {
        return Tblbillingcontact.TBLBILLINGCONTACT.PAYMENTMETHODID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getContactid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContactname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContactpersonposition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCompanyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTaxcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getCountryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCompanyphone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCellphone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCompanyfax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getContactemail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value15() {
        return getPaymentmethodid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value1(Integer value) {
        setContactid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value2(String value) {
        setContactname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value3(String value) {
        setContactpersonposition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value4(String value) {
        setCompanyname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value5(String value) {
        setTaxcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value6(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value7(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value8(Short value) {
        setCountryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value9(Integer value) {
        setCityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value10(String value) {
        setCityname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value11(String value) {
        setCompanyphone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value12(String value) {
        setCellphone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value13(String value) {
        setCompanyfax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value14(String value) {
        setContactemail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord value15(Byte value) {
        setPaymentmethodid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblbillingcontactRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Short value8, Integer value9, String value10, String value11, String value12, String value13, String value14, Byte value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblbillingcontactRecord
     */
    public TblbillingcontactRecord() {
        super(Tblbillingcontact.TBLBILLINGCONTACT);
    }

    /**
     * Create a detached, initialised TblbillingcontactRecord
     */
    public TblbillingcontactRecord(Integer contactid, String contactname, String contactpersonposition, String companyname, String taxcode, String address, String district, Short countryid, Integer cityid, String cityname, String companyphone, String cellphone, String companyfax, String contactemail, Byte paymentmethodid) {
        super(Tblbillingcontact.TBLBILLINGCONTACT);

        set(0, contactid);
        set(1, contactname);
        set(2, contactpersonposition);
        set(3, companyname);
        set(4, taxcode);
        set(5, address);
        set(6, district);
        set(7, countryid);
        set(8, cityid);
        set(9, cityname);
        set(10, companyphone);
        set(11, cellphone);
        set(12, companyfax);
        set(13, contactemail);
        set(14, paymentmethodid);
    }
}
