/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblcandidateBlacklist;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblcandidateBlacklistRecord extends UpdatableRecordImpl<TblcandidateBlacklistRecord> implements Record6<Integer, Integer, Byte, Integer, Timestamp, String> {

    private static final long serialVersionUID = 1530621844;

    /**
     * Setter for <code>vnw_core.tblcandidate_blacklist.empUserid</code>.
     */
    public void setEmpuserid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblcandidate_blacklist.empUserid</code>.
     */
    public Integer getEmpuserid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblcandidate_blacklist.cddUserid</code>.
     */
    public void setCdduserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblcandidate_blacklist.cddUserid</code>.
     */
    public Integer getCdduserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblcandidate_blacklist.applyType</code>. 0: sent directly; 1: apply online
     */
    public void setApplytype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblcandidate_blacklist.applyType</code>. 0: sent directly; 1: apply online
     */
    public Byte getApplytype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblcandidate_blacklist.applyId</code>.
     */
    public void setApplyid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblcandidate_blacklist.applyId</code>.
     */
    public Integer getApplyid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblcandidate_blacklist.createdDate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblcandidate_blacklist.createdDate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>vnw_core.tblcandidate_blacklist.empMsg</code>.
     */
    public void setEmpmsg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tblcandidate_blacklist.empMsg</code>.
     */
    public String getEmpmsg() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Byte, Integer, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Byte, Integer, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST.EMPUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST.CDDUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST.APPLYTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST.APPLYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST.EMPMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEmpuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCdduserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getApplytype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getApplyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmpmsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord value1(Integer value) {
        setEmpuserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord value2(Integer value) {
        setCdduserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord value3(Byte value) {
        setApplytype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord value4(Integer value) {
        setApplyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord value5(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord value6(String value) {
        setEmpmsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcandidateBlacklistRecord values(Integer value1, Integer value2, Byte value3, Integer value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblcandidateBlacklistRecord
     */
    public TblcandidateBlacklistRecord() {
        super(TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST);
    }

    /**
     * Create a detached, initialised TblcandidateBlacklistRecord
     */
    public TblcandidateBlacklistRecord(Integer empuserid, Integer cdduserid, Byte applytype, Integer applyid, Timestamp createddate, String empmsg) {
        super(TblcandidateBlacklist.TBLCANDIDATE_BLACKLIST);

        set(0, empuserid);
        set(1, cdduserid);
        set(2, applytype);
        set(3, applyid);
        set(4, createddate);
        set(5, empmsg);
    }
}
