/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.Tblcoverletter;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblcoverletterRecord extends UpdatableRecordImpl<TblcoverletterRecord> implements Record5<Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = 551428665;

    /**
     * Setter for <code>vnw_core.tblcoverletter.coverletterid</code>.
     */
    public void setCoverletterid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblcoverletter.coverletterid</code>.
     */
    public Integer getCoverletterid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblcoverletter.userid</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblcoverletter.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblcoverletter.coverlettertitle</code>.
     */
    public void setCoverlettertitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblcoverletter.coverlettertitle</code>.
     */
    public String getCoverlettertitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblcoverletter.coverletter</code>.
     */
    public void setCoverletter(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblcoverletter.coverletter</code>.
     */
    public String getCoverletter() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblcoverletter.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblcoverletter.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tblcoverletter.TBLCOVERLETTER.COVERLETTERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Tblcoverletter.TBLCOVERLETTER.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tblcoverletter.TBLCOVERLETTER.COVERLETTERTITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tblcoverletter.TBLCOVERLETTER.COVERLETTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Tblcoverletter.TBLCOVERLETTER.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCoverletterid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCoverlettertitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCoverletter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcoverletterRecord value1(Integer value) {
        setCoverletterid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcoverletterRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcoverletterRecord value3(String value) {
        setCoverlettertitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcoverletterRecord value4(String value) {
        setCoverletter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcoverletterRecord value5(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblcoverletterRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblcoverletterRecord
     */
    public TblcoverletterRecord() {
        super(Tblcoverletter.TBLCOVERLETTER);
    }

    /**
     * Create a detached, initialised TblcoverletterRecord
     */
    public TblcoverletterRecord(Integer coverletterid, Integer userid, String coverlettertitle, String coverletter, Timestamp createddate) {
        super(Tblcoverletter.TBLCOVERLETTER);

        set(0, coverletterid);
        set(1, userid);
        set(2, coverlettertitle);
        set(3, coverletter);
        set(4, createddate);
    }
}
