/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TbljobExtraprioritySchedule;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbljobExtrapriorityScheduleRecord extends UpdatableRecordImpl<TbljobExtrapriorityScheduleRecord> implements Record9<Integer, Integer, Short, Timestamp, Timestamp, Byte, Byte, Byte, Byte> {

    private static final long serialVersionUID = 211381634;

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.scheduleid</code>.
     */
    public void setScheduleid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.scheduleid</code>.
     */
    public Integer getScheduleid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.jobid</code>.
     */
    public void setJobid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.jobid</code>.
     */
    public Integer getJobid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.industryid</code>.
     */
    public void setIndustryid(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.industryid</code>.
     */
    public Short getIndustryid() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.expireddate</code>.
     */
    public void setExpireddate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.expireddate</code>.
     */
    public Timestamp getExpireddate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.duration</code>.
     */
    public void setDuration(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.duration</code>.
     */
    public Byte getDuration() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.isactive</code>.
     */
    public void setIsactive(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.isactive</code>.
     */
    public Byte getIsactive() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.inactive</code>.
     */
    public void setInactive(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.inactive</code>.
     */
    public Byte getInactive() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>vnw_core.tbljob_extrapriority_schedule.isdelete</code>.
     */
    public void setIsdelete(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>vnw_core.tbljob_extrapriority_schedule.isdelete</code>.
     */
    public Byte getIsdelete() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Short, Timestamp, Timestamp, Byte, Byte, Byte, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Short, Timestamp, Timestamp, Byte, Byte, Byte, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.SCHEDULEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.JOBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.INDUSTRYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.EXPIREDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.INACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE.ISDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getScheduleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getJobid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getIndustryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getExpireddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getInactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value1(Integer value) {
        setScheduleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value2(Integer value) {
        setJobid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value3(Short value) {
        setIndustryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value4(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value5(Timestamp value) {
        setExpireddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value6(Byte value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value7(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value8(Byte value) {
        setInactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord value9(Byte value) {
        setIsdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbljobExtrapriorityScheduleRecord values(Integer value1, Integer value2, Short value3, Timestamp value4, Timestamp value5, Byte value6, Byte value7, Byte value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbljobExtrapriorityScheduleRecord
     */
    public TbljobExtrapriorityScheduleRecord() {
        super(TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE);
    }

    /**
     * Create a detached, initialised TbljobExtrapriorityScheduleRecord
     */
    public TbljobExtrapriorityScheduleRecord(Integer scheduleid, Integer jobid, Short industryid, Timestamp createddate, Timestamp expireddate, Byte duration, Byte isactive, Byte inactive, Byte isdelete) {
        super(TbljobExtraprioritySchedule.TBLJOB_EXTRAPRIORITY_SCHEDULE);

        set(0, scheduleid);
        set(1, jobid);
        set(2, industryid);
        set(3, createddate);
        set(4, expireddate);
        set(5, duration);
        set(6, isactive);
        set(7, inactive);
        set(8, isdelete);
    }
}
