/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblrefNationalitycode;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefNationalitycodeRecord extends UpdatableRecordImpl<TblrefNationalitycodeRecord> implements Record2<Byte, String> {

    private static final long serialVersionUID = 1327416184;

    /**
     * Setter for <code>vnw_core.tblref_nationalitycode.nationalityid</code>.
     */
    public void setNationalityid(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_nationalitycode.nationalityid</code>.
     */
    public Byte getNationalityid() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblref_nationalitycode.nationalitycode</code>.
     */
    public void setNationalitycode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_nationalitycode.nationalitycode</code>.
     */
    public String getNationalitycode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Byte, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Byte, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field1() {
        return TblrefNationalitycode.TBLREF_NATIONALITYCODE.NATIONALITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblrefNationalitycode.TBLREF_NATIONALITYCODE.NATIONALITYCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value1() {
        return getNationalityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNationalitycode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefNationalitycodeRecord value1(Byte value) {
        setNationalityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefNationalitycodeRecord value2(String value) {
        setNationalitycode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefNationalitycodeRecord values(Byte value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblrefNationalitycodeRecord
     */
    public TblrefNationalitycodeRecord() {
        super(TblrefNationalitycode.TBLREF_NATIONALITYCODE);
    }

    /**
     * Create a detached, initialised TblrefNationalitycodeRecord
     */
    public TblrefNationalitycodeRecord(Byte nationalityid, String nationalitycode) {
        super(TblrefNationalitycode.TBLREF_NATIONALITYCODE);

        set(0, nationalityid);
        set(1, nationalitycode);
    }
}
