/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblrefSearchtimes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefSearchtimesRecord extends UpdatableRecordImpl<TblrefSearchtimesRecord> implements Record3<UInteger, Integer, Timestamp> {

    private static final long serialVersionUID = 1159338337;

    /**
     * Setter for <code>vnw_core.tblref_searchTimes.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_searchTimes.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblref_searchTimes.NumberOfSearch</code>.
     */
    public void setNumberofsearch(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_searchTimes.NumberOfSearch</code>.
     */
    public Integer getNumberofsearch() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblref_searchTimes.UpdateTime</code>.
     */
    public void setUpdatetime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_searchTimes.UpdateTime</code>.
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, Integer, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, Integer, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TblrefSearchtimes.TBLREF_SEARCHTIMES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblrefSearchtimes.TBLREF_SEARCHTIMES.NUMBEROFSEARCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TblrefSearchtimes.TBLREF_SEARCHTIMES.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNumberofsearch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefSearchtimesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefSearchtimesRecord value2(Integer value) {
        setNumberofsearch(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefSearchtimesRecord value3(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefSearchtimesRecord values(UInteger value1, Integer value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblrefSearchtimesRecord
     */
    public TblrefSearchtimesRecord() {
        super(TblrefSearchtimes.TBLREF_SEARCHTIMES);
    }

    /**
     * Create a detached, initialised TblrefSearchtimesRecord
     */
    public TblrefSearchtimesRecord(UInteger id, Integer numberofsearch, Timestamp updatetime) {
        super(TblrefSearchtimes.TBLREF_SEARCHTIMES);

        set(0, id);
        set(1, numberofsearch);
        set(2, updatetime);
    }
}
