/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblrefLanguageselectedApplyjobcode;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefLanguageselectedApplyjobcodeRecord extends UpdatableRecordImpl<TblrefLanguageselectedApplyjobcodeRecord> implements Record3<Byte, String, Short> {

    private static final long serialVersionUID = 1278435665;

    /**
     * Setter for <code>vnw_core.tblref_languageselected_applyjobcode.selectedid</code>.
     */
    public void setSelectedid(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_languageselected_applyjobcode.selectedid</code>.
     */
    public Byte getSelectedid() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblref_languageselected_applyjobcode.selectedcode</code>.
     */
    public void setSelectedcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_languageselected_applyjobcode.selectedcode</code>.
     */
    public String getSelectedcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblref_languageselected_applyjobcode.selectedorder</code>.
     */
    public void setSelectedorder(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_languageselected_applyjobcode.selectedorder</code>.
     */
    public Short getSelectedorder() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Byte, String, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Byte, String, Short> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field1() {
        return TblrefLanguageselectedApplyjobcode.TBLREF_LANGUAGESELECTED_APPLYJOBCODE.SELECTEDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblrefLanguageselectedApplyjobcode.TBLREF_LANGUAGESELECTED_APPLYJOBCODE.SELECTEDCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return TblrefLanguageselectedApplyjobcode.TBLREF_LANGUAGESELECTED_APPLYJOBCODE.SELECTEDORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value1() {
        return getSelectedid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSelectedcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getSelectedorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefLanguageselectedApplyjobcodeRecord value1(Byte value) {
        setSelectedid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefLanguageselectedApplyjobcodeRecord value2(String value) {
        setSelectedcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefLanguageselectedApplyjobcodeRecord value3(Short value) {
        setSelectedorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefLanguageselectedApplyjobcodeRecord values(Byte value1, String value2, Short value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblrefLanguageselectedApplyjobcodeRecord
     */
    public TblrefLanguageselectedApplyjobcodeRecord() {
        super(TblrefLanguageselectedApplyjobcode.TBLREF_LANGUAGESELECTED_APPLYJOBCODE);
    }

    /**
     * Create a detached, initialised TblrefLanguageselectedApplyjobcodeRecord
     */
    public TblrefLanguageselectedApplyjobcodeRecord(Byte selectedid, String selectedcode, Short selectedorder) {
        super(TblrefLanguageselectedApplyjobcode.TBLREF_LANGUAGESELECTED_APPLYJOBCODE);

        set(0, selectedid);
        set(1, selectedcode);
        set(2, selectedorder);
    }
}
