/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblresumeAlert;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblresumeAlertRecord extends UpdatableRecordImpl<TblresumeAlertRecord> {

    private static final long serialVersionUID = -1330392671;

    /**
     * Setter for <code>vnw_core.tblresume_alert.resumealertid</code>.
     */
    public void setResumealertid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.resumealertid</code>.
     */
    public Integer getResumealertid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.periodtypeid</code>.
     */
    public void setPeriodtypeid(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.periodtypeid</code>.
     */
    public Byte getPeriodtypeid() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.noofdays</code>.
     */
    public void setNoofdays(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.noofdays</code>.
     */
    public Integer getNoofdays() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.sendingdate</code>.
     */
    public void setSendingdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.sendingdate</code>.
     */
    public Timestamp getSendingdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.userid</code>.
     */
    public void setUserid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.genderid</code>.
     */
    public void setGenderid(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.genderid</code>.
     */
    public Byte getGenderid() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.schoolid</code>.
     */
    public void setSchoolid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.schoolid</code>.
     */
    public Integer getSchoolid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.languageproficiencyid</code>.
     */
    public void setLanguageproficiencyid(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.languageproficiencyid</code>.
     */
    public Short getLanguageproficiencyid() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.proficiency_id</code>.
     */
    public void setProficiencyId(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.proficiency_id</code>.
     */
    public Short getProficiencyId() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.typeworkingid</code>.
     */
    public void setTypeworkingid(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.typeworkingid</code>.
     */
    public Short getTypeworkingid() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.highestdegreeid</code>.
     */
    public void setHighestdegreeid(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.highestdegreeid</code>.
     */
    public Short getHighestdegreeid() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.username</code>.
     */
    public void setUsername(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.username</code>.
     */
    public String getUsername() {
        return (String) get(11);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.useremail</code>.
     */
    public void setUseremail(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.useremail</code>.
     */
    public String getUseremail() {
        return (String) get(12);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.firstname</code>.
     */
    public void setFirstname(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(13);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.lastname</code>.
     */
    public void setLastname(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.lastname</code>.
     */
    public String getLastname() {
        return (String) get(14);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.industryid</code>.
     */
    public void setIndustryid(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.industryid</code>.
     */
    public Short getIndustryid() {
        return (Short) get(15);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.noofyearexperience</code>.
     */
    public void setNoofyearexperience(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.noofyearexperience</code>.
     */
    public Short getNoofyearexperience() {
        return (Short) get(16);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.salary_min</code>.
     */
    public void setSalaryMin(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.salary_min</code>.
     */
    public Integer getSalaryMin() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.salary_max</code>.
     */
    public void setSalaryMax(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.salary_max</code>.
     */
    public Integer getSalaryMax() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.age_min</code>.
     */
    public void setAgeMin(Short value) {
        set(19, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.age_min</code>.
     */
    public Short getAgeMin() {
        return (Short) get(19);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.age_max</code>.
     */
    public void setAgeMax(Short value) {
        set(20, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.age_max</code>.
     */
    public Short getAgeMax() {
        return (Short) get(20);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(21);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.noofdayresumeupdated</code>.
     */
    public void setNoofdayresumeupdated(Short value) {
        set(22, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.noofdayresumeupdated</code>.
     */
    public Short getNoofdayresumeupdated() {
        return (Short) get(22);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.durationdays</code>.
     */
    public void setDurationdays(Short value) {
        set(23, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.durationdays</code>.
     */
    public Short getDurationdays() {
        return (Short) get(23);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.expireddate</code>.
     */
    public void setExpireddate(Timestamp value) {
        set(24, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.expireddate</code>.
     */
    public Timestamp getExpireddate() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.keyword</code>.
     */
    public void setKeyword(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(25);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.mustmatchid</code>.
     */
    public void setMustmatchid(Byte value) {
        set(26, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.mustmatchid</code>.
     */
    public Byte getMustmatchid() {
        return (Byte) get(26);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.cityid</code>.
     */
    public void setCityid(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.cityid</code>.
     */
    public Integer getCityid() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.sqlstring</code>.
     */
    public void setSqlstring(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.sqlstring</code>.
     */
    public String getSqlstring() {
        return (String) get(28);
    }

    /**
     * Setter for <code>vnw_core.tblresume_alert.joblevelid</code>.
     */
    public void setJoblevelid(Byte value) {
        set(29, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_alert.joblevelid</code>.
     */
    public Byte getJoblevelid() {
        return (Byte) get(29);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblresumeAlertRecord
     */
    public TblresumeAlertRecord() {
        super(TblresumeAlert.TBLRESUME_ALERT);
    }

    /**
     * Create a detached, initialised TblresumeAlertRecord
     */
    public TblresumeAlertRecord(Integer resumealertid, Byte periodtypeid, Integer noofdays, Timestamp sendingdate, Integer userid, Byte genderid, Integer schoolid, Short languageproficiencyid, Short proficiencyId, Short typeworkingid, Short highestdegreeid, String username, String useremail, String firstname, String lastname, Short industryid, Short noofyearexperience, Integer salaryMin, Integer salaryMax, Short ageMin, Short ageMax, Timestamp createddate, Short noofdayresumeupdated, Short durationdays, Timestamp expireddate, String keyword, Byte mustmatchid, Integer cityid, String sqlstring, Byte joblevelid) {
        super(TblresumeAlert.TBLRESUME_ALERT);

        set(0, resumealertid);
        set(1, periodtypeid);
        set(2, noofdays);
        set(3, sendingdate);
        set(4, userid);
        set(5, genderid);
        set(6, schoolid);
        set(7, languageproficiencyid);
        set(8, proficiencyId);
        set(9, typeworkingid);
        set(10, highestdegreeid);
        set(11, username);
        set(12, useremail);
        set(13, firstname);
        set(14, lastname);
        set(15, industryid);
        set(16, noofyearexperience);
        set(17, salaryMin);
        set(18, salaryMax);
        set(19, ageMin);
        set(20, ageMax);
        set(21, createddate);
        set(22, noofdayresumeupdated);
        set(23, durationdays);
        set(24, expireddate);
        set(25, keyword);
        set(26, mustmatchid);
        set(27, cityid);
        set(28, sqlstring);
        set(29, joblevelid);
    }
}
