/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblrefJobfunction;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefJobfunctionRecord extends UpdatableRecordImpl<TblrefJobfunctionRecord> implements Record5<Integer, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 2077238482;

    /**
     * Setter for <code>vnw_core.tblref_jobfunction.jobfunctionid</code>.
     */
    public void setJobfunctionid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_jobfunction.jobfunctionid</code>.
     */
    public Integer getJobfunctionid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblref_jobfunction.languageid</code>.
     */
    public void setLanguageid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_jobfunction.languageid</code>.
     */
    public Integer getLanguageid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblref_jobfunction.industryid</code>.
     */
    public void setIndustryid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_jobfunction.industryid</code>.
     */
    public Integer getIndustryid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblref_jobfunction.jobfuncname</code>.
     */
    public void setJobfuncname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_jobfunction.jobfuncname</code>.
     */
    public String getJobfuncname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblref_jobfunction.jobfuncorder</code>.
     */
    public void setJobfuncorder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblref_jobfunction.jobfuncorder</code>.
     */
    public Integer getJobfuncorder() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblrefJobfunction.TBLREF_JOBFUNCTION.JOBFUNCTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblrefJobfunction.TBLREF_JOBFUNCTION.LANGUAGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblrefJobfunction.TBLREF_JOBFUNCTION.INDUSTRYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TblrefJobfunction.TBLREF_JOBFUNCTION.JOBFUNCNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblrefJobfunction.TBLREF_JOBFUNCTION.JOBFUNCORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getJobfunctionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLanguageid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIndustryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getJobfuncname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getJobfuncorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefJobfunctionRecord value1(Integer value) {
        setJobfunctionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefJobfunctionRecord value2(Integer value) {
        setLanguageid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefJobfunctionRecord value3(Integer value) {
        setIndustryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefJobfunctionRecord value4(String value) {
        setJobfuncname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefJobfunctionRecord value5(Integer value) {
        setJobfuncorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefJobfunctionRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblrefJobfunctionRecord
     */
    public TblrefJobfunctionRecord() {
        super(TblrefJobfunction.TBLREF_JOBFUNCTION);
    }

    /**
     * Create a detached, initialised TblrefJobfunctionRecord
     */
    public TblrefJobfunctionRecord(Integer jobfunctionid, Integer languageid, Integer industryid, String jobfuncname, Integer jobfuncorder) {
        super(TblrefJobfunction.TBLREF_JOBFUNCTION);

        set(0, jobfunctionid);
        set(1, languageid);
        set(2, industryid);
        set(3, jobfuncname);
        set(4, jobfuncorder);
    }
}
