/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblresumeViewedTracking;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblresumeViewedTrackingRecord extends UpdatableRecordImpl<TblresumeViewedTrackingRecord> implements Record5<UInteger, UInteger, String, UInteger, Timestamp> {

    private static final long serialVersionUID = 1268061549;

    /**
     * Setter for <code>vnw_core.tblresume_viewed_tracking.entryid</code>.
     */
    public void setEntryid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_viewed_tracking.entryid</code>.
     */
    public UInteger getEntryid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblresume_viewed_tracking.userid</code>.
     */
    public void setUserid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_viewed_tracking.userid</code>.
     */
    public UInteger getUserid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblresume_viewed_tracking.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_viewed_tracking.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblresume_viewed_tracking.totalviewed</code>.
     */
    public void setTotalviewed(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_viewed_tracking.totalviewed</code>.
     */
    public UInteger getTotalviewed() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblresume_viewed_tracking.createdate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblresume_viewed_tracking.createdate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, String, UInteger, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, String, UInteger, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING.ENTRYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING.TOTALVIEWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getEntryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getTotalviewed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeViewedTrackingRecord value1(UInteger value) {
        setEntryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeViewedTrackingRecord value2(UInteger value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeViewedTrackingRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeViewedTrackingRecord value4(UInteger value) {
        setTotalviewed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeViewedTrackingRecord value5(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeViewedTrackingRecord values(UInteger value1, UInteger value2, String value3, UInteger value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblresumeViewedTrackingRecord
     */
    public TblresumeViewedTrackingRecord() {
        super(TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING);
    }

    /**
     * Create a detached, initialised TblresumeViewedTrackingRecord
     */
    public TblresumeViewedTrackingRecord(UInteger entryid, UInteger userid, String username, UInteger totalviewed, Timestamp createdate) {
        super(TblresumeViewedTracking.TBLRESUME_VIEWED_TRACKING);

        set(0, entryid);
        set(1, userid);
        set(2, username);
        set(3, totalviewed);
        set(4, createdate);
    }
}
