/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.Tblso;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblsoRecord extends UpdatableRecordImpl<TblsoRecord> implements Record18<Integer, String, Integer, Integer, String, Timestamp, Integer, Short, Byte, Byte, Timestamp, Byte, Timestamp, Integer, String, Double, String, String> {

    private static final long serialVersionUID = -724327514;

    /**
     * Setter for <code>vnw_core.tblso.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblso.po_no</code>. currently NOT use
     */
    public void setPoNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.po_no</code>. currently NOT use
     */
    public String getPoNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblso.po_id</code>.
     */
    public void setPoId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.po_id</code>.
     */
    public Integer getPoId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblso.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblso.so_no</code>. auto-generate, currently NOT use
     */
    public void setSoNo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.so_no</code>. auto-generate, currently NOT use
     */
    public String getSoNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vnw_core.tblso.active_date</code>. date that user use service
     */
    public void setActiveDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.active_date</code>. date that user use service
     */
    public Timestamp getActiveDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>vnw_core.tblso.po_product_id</code>.
     */
    public void setPoProductId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.po_product_id</code>.
     */
    public Integer getPoProductId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>vnw_core.tblso.quantity</code>.
     */
    public void setQuantity(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.quantity</code>.
     */
    public Short getQuantity() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>vnw_core.tblso.is_free</code>.  0: not free , 1: free
     */
    public void setIsFree(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.is_free</code>.  0: not free , 1: free
     */
    public Byte getIsFree() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>vnw_core.tblso.is_sent_to_crm</code>. 1: sent
     */
    public void setIsSentToCrm(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.is_sent_to_crm</code>. 1: sent
     */
    public Byte getIsSentToCrm() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>vnw_core.tblso.crm_sent_date</code>.
     */
    public void setCrmSentDate(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.crm_sent_date</code>.
     */
    public Timestamp getCrmSentDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>vnw_core.tblso.is_moving_to_crm</code>. 1: sending
     */
    public void setIsMovingToCrm(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.is_moving_to_crm</code>. 1: sending
     */
    public Byte getIsMovingToCrm() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>vnw_core.tblso.crm_start_sending_date</code>.
     */
    public void setCrmStartSendingDate(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.crm_start_sending_date</code>.
     */
    public Timestamp getCrmStartSendingDate() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>vnw_core.tblso.object_id</code>. jobid, RV_id, logo banner id
     */
    public void setObjectId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.object_id</code>. jobid, RV_id, logo banner id
     */
    public Integer getObjectId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>vnw_core.tblso.object_code</code>. service_code
     */
    public void setObjectCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.object_code</code>. service_code
     */
    public String getObjectCode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>vnw_core.tblso.unit_price</code>.
     */
    public void setUnitPrice(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.unit_price</code>.
     */
    public Double getUnitPrice() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>vnw_core.tblso.client_ip</code>.
     */
    public void setClientIp(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.client_ip</code>.
     */
    public String getClientIp() {
        return (String) get(16);
    }

    /**
     * Setter for <code>vnw_core.tblso.so_crm_id</code>.
     */
    public void setSoCrmId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>vnw_core.tblso.so_crm_id</code>.
     */
    public String getSoCrmId() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, Integer, Integer, String, Timestamp, Integer, Short, Byte, Byte, Timestamp, Byte, Timestamp, Integer, String, Double, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, Integer, Integer, String, Timestamp, Integer, Short, Byte, Byte, Timestamp, Byte, Timestamp, Integer, String, Double, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tblso.TBLSO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tblso.TBLSO.PO_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tblso.TBLSO.PO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tblso.TBLSO.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Tblso.TBLSO.SO_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Tblso.TBLSO.ACTIVE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Tblso.TBLSO.PO_PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return Tblso.TBLSO.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Tblso.TBLSO.IS_FREE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Tblso.TBLSO.IS_SENT_TO_CRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Tblso.TBLSO.CRM_SENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return Tblso.TBLSO.IS_MOVING_TO_CRM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Tblso.TBLSO.CRM_START_SENDING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Tblso.TBLSO.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Tblso.TBLSO.OBJECT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field16() {
        return Tblso.TBLSO.UNIT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Tblso.TBLSO.CLIENT_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Tblso.TBLSO.SO_CRM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPoNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSoNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getActiveDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPoProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsFree();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getIsSentToCrm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCrmSentDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getIsMovingToCrm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCrmStartSendingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getObjectCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value16() {
        return getUnitPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getClientIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getSoCrmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value2(String value) {
        setPoNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value3(Integer value) {
        setPoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value4(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value5(String value) {
        setSoNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value6(Timestamp value) {
        setActiveDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value7(Integer value) {
        setPoProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value8(Short value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value9(Byte value) {
        setIsFree(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value10(Byte value) {
        setIsSentToCrm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value11(Timestamp value) {
        setCrmSentDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value12(Byte value) {
        setIsMovingToCrm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value13(Timestamp value) {
        setCrmStartSendingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value14(Integer value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value15(String value) {
        setObjectCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value16(Double value) {
        setUnitPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value17(String value) {
        setClientIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord value18(String value) {
        setSoCrmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsoRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, Timestamp value6, Integer value7, Short value8, Byte value9, Byte value10, Timestamp value11, Byte value12, Timestamp value13, Integer value14, String value15, Double value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblsoRecord
     */
    public TblsoRecord() {
        super(Tblso.TBLSO);
    }

    /**
     * Create a detached, initialised TblsoRecord
     */
    public TblsoRecord(Integer id, String poNo, Integer poId, Integer productId, String soNo, Timestamp activeDate, Integer poProductId, Short quantity, Byte isFree, Byte isSentToCrm, Timestamp crmSentDate, Byte isMovingToCrm, Timestamp crmStartSendingDate, Integer objectId, String objectCode, Double unitPrice, String clientIp, String soCrmId) {
        super(Tblso.TBLSO);

        set(0, id);
        set(1, poNo);
        set(2, poId);
        set(3, productId);
        set(4, soNo);
        set(5, activeDate);
        set(6, poProductId);
        set(7, quantity);
        set(8, isFree);
        set(9, isSentToCrm);
        set(10, crmSentDate);
        set(11, isMovingToCrm);
        set(12, crmStartSendingDate);
        set(13, objectId);
        set(14, objectCode);
        set(15, unitPrice);
        set(16, clientIp);
        set(17, soCrmId);
    }
}
