/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblscreenTestJsAnswer;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblscreenTestJsAnswerRecord extends UpdatableRecordImpl<TblscreenTestJsAnswerRecord> implements Record3<UInteger, UInteger, Byte> {

    private static final long serialVersionUID = -434665290;

    /**
     * Setter for <code>vnw_core.tblscreen_test_js_answer.jsTestId</code>.
     */
    public void setJstestid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_js_answer.jsTestId</code>.
     */
    public UInteger getJstestid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_js_answer.questionId</code>. question id
     */
    public void setQuestionid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_js_answer.questionId</code>. question id
     */
    public UInteger getQuestionid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_js_answer.optionId</code>.
     */
    public void setOptionid(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_js_answer.optionId</code>.
     */
    public Byte getOptionid() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TblscreenTestJsAnswer.TBLSCREEN_TEST_JS_ANSWER.JSTESTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TblscreenTestJsAnswer.TBLSCREEN_TEST_JS_ANSWER.QUESTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return TblscreenTestJsAnswer.TBLSCREEN_TEST_JS_ANSWER.OPTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getJstestid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getOptionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestJsAnswerRecord value1(UInteger value) {
        setJstestid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestJsAnswerRecord value2(UInteger value) {
        setQuestionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestJsAnswerRecord value3(Byte value) {
        setOptionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestJsAnswerRecord values(UInteger value1, UInteger value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblscreenTestJsAnswerRecord
     */
    public TblscreenTestJsAnswerRecord() {
        super(TblscreenTestJsAnswer.TBLSCREEN_TEST_JS_ANSWER);
    }

    /**
     * Create a detached, initialised TblscreenTestJsAnswerRecord
     */
    public TblscreenTestJsAnswerRecord(UInteger jstestid, UInteger questionid, Byte optionid) {
        super(TblscreenTestJsAnswer.TBLSCREEN_TEST_JS_ANSWER);

        set(0, jstestid);
        set(1, questionid);
        set(2, optionid);
    }
}
