/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblsaveSearch;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblsaveSearchRecord extends UpdatableRecordImpl<TblsaveSearchRecord> implements Record7<Integer, Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2025701346;

    /**
     * Setter for <code>vnw_core.tblsave_search.entryid</code>.
     */
    public void setEntryid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.entryid</code>.
     */
    public Integer getEntryid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblsave_search.userid</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblsave_search.descsave</code>.
     */
    public void setDescsave(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.descsave</code>.
     */
    public String getDescsave() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblsave_search.objectform</code>.
     */
    public void setObjectform(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.objectform</code>.
     */
    public String getObjectform() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblsave_search.sqlstring</code>.
     */
    public void setSqlstring(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.sqlstring</code>.
     */
    public String getSqlstring() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vnw_core.tblsave_search.createddate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.createddate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>vnw_core.tblsave_search.lastupdated</code>.
     */
    public void setLastupdated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tblsave_search.lastupdated</code>.
     */
    public Timestamp getLastupdated() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblsaveSearch.TBLSAVE_SEARCH.ENTRYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblsaveSearch.TBLSAVE_SEARCH.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblsaveSearch.TBLSAVE_SEARCH.DESCSAVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TblsaveSearch.TBLSAVE_SEARCH.OBJECTFORM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblsaveSearch.TBLSAVE_SEARCH.SQLSTRING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TblsaveSearch.TBLSAVE_SEARCH.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TblsaveSearch.TBLSAVE_SEARCH.LASTUPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEntryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescsave();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getObjectform();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSqlstring();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value1(Integer value) {
        setEntryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value3(String value) {
        setDescsave(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value4(String value) {
        setObjectform(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value5(String value) {
        setSqlstring(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value6(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord value7(Timestamp value) {
        setLastupdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblsaveSearchRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblsaveSearchRecord
     */
    public TblsaveSearchRecord() {
        super(TblsaveSearch.TBLSAVE_SEARCH);
    }

    /**
     * Create a detached, initialised TblsaveSearchRecord
     */
    public TblsaveSearchRecord(Integer entryid, Integer userid, String descsave, String objectform, String sqlstring, Timestamp createddate, Timestamp lastupdated) {
        super(TblsaveSearch.TBLSAVE_SEARCH);

        set(0, entryid);
        set(1, userid);
        set(2, descsave);
        set(3, objectform);
        set(4, sqlstring);
        set(5, createddate);
        set(6, lastupdated);
    }
}
