/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TblscreenTestQuestion;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblscreenTestQuestionRecord extends UpdatableRecordImpl<TblscreenTestQuestionRecord> implements Record7<UInteger, UInteger, UByte, UByte, String, UByte, Byte> {

    private static final long serialVersionUID = 1963773879;

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.testId</code>.
     */
    public void setTestid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.testId</code>.
     */
    public UInteger getTestid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.questionId</code>. id of question, uniqe in a test
     */
    public void setQuestionid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.questionId</code>. id of question, uniqe in a test
     */
    public UInteger getQuestionid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.questionOrder</code>. order of question in a test
     */
    public void setQuestionorder(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.questionOrder</code>. order of question in a test
     */
    public UByte getQuestionorder() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.questionType</code>.  1: multichoice 2: free text
     */
    public void setQuestiontype(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.questionType</code>.  1: multichoice 2: free text
     */
    public UByte getQuestiontype() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.content</code>. question content
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.content</code>. question content
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.correctOptionId</code>. 0: none -> not scored question; >0: is scored question and the correct optionId is this number
     */
    public void setCorrectoptionid(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.correctOptionId</code>. 0: none -> not scored question; >0: is scored question and the correct optionId is this number
     */
    public UByte getCorrectoptionid() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>vnw_core.tblscreen_test_question.score</code>. question score
     */
    public void setScore(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tblscreen_test_question.score</code>. question score
     */
    public Byte getScore() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, UByte, UByte, String, UByte, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, UByte, UByte, String, UByte, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.TESTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.QUESTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.QUESTIONORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.QUESTIONTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.CORRECTOPTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getTestid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getQuestionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getQuestionorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getQuestiontype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getCorrectoptionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value1(UInteger value) {
        setTestid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value2(UInteger value) {
        setQuestionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value3(UByte value) {
        setQuestionorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value4(UByte value) {
        setQuestiontype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value5(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value6(UByte value) {
        setCorrectoptionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord value7(Byte value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblscreenTestQuestionRecord values(UInteger value1, UInteger value2, UByte value3, UByte value4, String value5, UByte value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblscreenTestQuestionRecord
     */
    public TblscreenTestQuestionRecord() {
        super(TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION);
    }

    /**
     * Create a detached, initialised TblscreenTestQuestionRecord
     */
    public TblscreenTestQuestionRecord(UInteger testid, UInteger questionid, UByte questionorder, UByte questiontype, String content, UByte correctoptionid, Byte score) {
        super(TblscreenTestQuestion.TBLSCREEN_TEST_QUESTION);

        set(0, testid);
        set(1, questionid);
        set(2, questionorder);
        set(3, questiontype);
        set(4, content);
        set(5, correctoptionid);
        set(6, score);
    }
}
