/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TbltrackUser_1;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbltrackUser_1Record extends TableRecordImpl<TbltrackUser_1Record> implements Record6<UByte, String, UInteger, UByte, UInteger, Timestamp> {

    private static final long serialVersionUID = -679855684;

    /**
     * Setter for <code>vnw_core.tbltrack_user_1.versionId</code>.
     */
    public void setVersionid(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_user_1.versionId</code>.
     */
    public UByte getVersionid() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_user_1.appId</code>.
     */
    public void setAppid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_user_1.appId</code>.
     */
    public String getAppid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_user_1.userid</code>.
     */
    public void setUserid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_user_1.userid</code>.
     */
    public UInteger getUserid() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_user_1.functionId</code>.
     */
    public void setFunctionid(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_user_1.functionId</code>.
     */
    public UByte getFunctionid() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_user_1.objectId</code>.
     */
    public void setObjectid(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_user_1.objectId</code>.
     */
    public UInteger getObjectid() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_user_1.accessTime</code>.
     */
    public void setAccesstime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_user_1.accessTime</code>.
     */
    public Timestamp getAccesstime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UByte, String, UInteger, UByte, UInteger, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UByte, String, UInteger, UByte, UInteger, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return TbltrackUser_1.TBLTRACK_USER_1.VERSIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbltrackUser_1.TBLTRACK_USER_1.APPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return TbltrackUser_1.TBLTRACK_USER_1.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return TbltrackUser_1.TBLTRACK_USER_1.FUNCTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return TbltrackUser_1.TBLTRACK_USER_1.OBJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TbltrackUser_1.TBLTRACK_USER_1.ACCESSTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getVersionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getFunctionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getObjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getAccesstime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record value1(UByte value) {
        setVersionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record value2(String value) {
        setAppid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record value3(UInteger value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record value4(UByte value) {
        setFunctionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record value5(UInteger value) {
        setObjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record value6(Timestamp value) {
        setAccesstime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackUser_1Record values(UByte value1, String value2, UInteger value3, UByte value4, UInteger value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbltrackUser_1Record
     */
    public TbltrackUser_1Record() {
        super(TbltrackUser_1.TBLTRACK_USER_1);
    }

    /**
     * Create a detached, initialised TbltrackUser_1Record
     */
    public TbltrackUser_1Record(UByte versionid, String appid, UInteger userid, UByte functionid, UInteger objectid, Timestamp accesstime) {
        super(TbltrackUser_1.TBLTRACK_USER_1);

        set(0, versionid);
        set(1, appid);
        set(2, userid);
        set(3, functionid);
        set(4, objectid);
        set(5, accesstime);
    }
}
