/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TbltrackEmployerWebsite;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbltrackEmployerWebsiteRecord extends UpdatableRecordImpl<TbltrackEmployerWebsiteRecord> implements Record6<Integer, String, Timestamp, Timestamp, UInteger, UInteger> {

    private static final long serialVersionUID = -1771973737;

    /**
     * Setter for <code>vnw_core.tbltrack_employer_website.companyid</code>.
     */
    public void setCompanyid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_employer_website.companyid</code>.
     */
    public Integer getCompanyid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_employer_website.profileBaseName</code>. name of profile website on vietnamework ex : www.vietnamworks.com/employer/profileBaseName
     */
    public void setProfilebasename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_employer_website.profileBaseName</code>. name of profile website on vietnamework ex : www.vietnamworks.com/employer/profileBaseName
     */
    public String getProfilebasename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_employer_website.createdDate</code>.  created date of website
     */
    public void setCreateddate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_employer_website.createdDate</code>.  created date of website
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_employer_website.lastUpdatedDate</code>.  last updated date of website
     */
    public void setLastupdateddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_employer_website.lastUpdatedDate</code>.  last updated date of website
     */
    public Timestamp getLastupdateddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_employer_website.noofView</code>.  no of view
     */
    public void setNoofview(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_employer_website.noofView</code>.  no of view
     */
    public UInteger getNoofview() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>vnw_core.tbltrack_employer_website.noofShare</code>.  no of share
     */
    public void setNoofshare(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tbltrack_employer_website.noofShare</code>.  no of share
     */
    public UInteger getNoofshare() {
        return (UInteger) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Timestamp, UInteger, UInteger> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Timestamp, UInteger, UInteger> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE.COMPANYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE.PROFILEBASENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE.LASTUPDATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE.NOOFVIEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE.NOOFSHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProfilebasename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLastupdateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getNoofview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getNoofshare();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord value1(Integer value) {
        setCompanyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord value2(String value) {
        setProfilebasename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord value3(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord value4(Timestamp value) {
        setLastupdateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord value5(UInteger value) {
        setNoofview(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord value6(UInteger value) {
        setNoofshare(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackEmployerWebsiteRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, UInteger value5, UInteger value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbltrackEmployerWebsiteRecord
     */
    public TbltrackEmployerWebsiteRecord() {
        super(TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE);
    }

    /**
     * Create a detached, initialised TbltrackEmployerWebsiteRecord
     */
    public TbltrackEmployerWebsiteRecord(Integer companyid, String profilebasename, Timestamp createddate, Timestamp lastupdateddate, UInteger noofview, UInteger noofshare) {
        super(TbltrackEmployerWebsite.TBLTRACK_EMPLOYER_WEBSITE);

        set(0, companyid);
        set(1, profilebasename);
        set(2, createddate);
        set(3, lastupdateddate);
        set(4, noofview);
        set(5, noofshare);
    }
}
