/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TbluserRestriction;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbluserRestrictionRecord extends UpdatableRecordImpl<TbluserRestrictionRecord> implements Record5<UInteger, UInteger, UInteger, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1447400113;

    /**
     * Setter for <code>vnw_core.tbluser_restriction.entryid</code>.
     */
    public void setEntryid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_restriction.entryid</code>.
     */
    public UInteger getEntryid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>vnw_core.tbluser_restriction.userid</code>.
     */
    public void setUserid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_restriction.userid</code>.
     */
    public UInteger getUserid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>vnw_core.tbluser_restriction.employerid</code>.
     */
    public void setEmployerid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_restriction.employerid</code>.
     */
    public UInteger getEmployerid() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>vnw_core.tbluser_restriction.createdate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_restriction.createdate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>vnw_core.tbluser_restriction.lastdatelogin</code>.
     */
    public void setLastdatelogin(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_restriction.lastdatelogin</code>.
     */
    public Timestamp getLastdatelogin() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UInteger, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UInteger, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TbluserRestriction.TBLUSER_RESTRICTION.ENTRYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TbluserRestriction.TBLUSER_RESTRICTION.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return TbluserRestriction.TBLUSER_RESTRICTION.EMPLOYERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TbluserRestriction.TBLUSER_RESTRICTION.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TbluserRestriction.TBLUSER_RESTRICTION.LASTDATELOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getEntryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getEmployerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastdatelogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserRestrictionRecord value1(UInteger value) {
        setEntryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserRestrictionRecord value2(UInteger value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserRestrictionRecord value3(UInteger value) {
        setEmployerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserRestrictionRecord value4(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserRestrictionRecord value5(Timestamp value) {
        setLastdatelogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserRestrictionRecord values(UInteger value1, UInteger value2, UInteger value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbluserRestrictionRecord
     */
    public TbluserRestrictionRecord() {
        super(TbluserRestriction.TBLUSER_RESTRICTION);
    }

    /**
     * Create a detached, initialised TbluserRestrictionRecord
     */
    public TbluserRestrictionRecord(UInteger entryid, UInteger userid, UInteger employerid, Timestamp createdate, Timestamp lastdatelogin) {
        super(TbluserRestriction.TBLUSER_RESTRICTION);

        set(0, entryid);
        set(1, userid);
        set(2, employerid);
        set(3, createdate);
        set(4, lastdatelogin);
    }
}
