/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables.records;


import com.vnw.data.jooq.tables.TbluserReminder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbluserReminderRecord extends UpdatableRecordImpl<TbluserReminderRecord> implements Record8<Integer, String, String, Integer, String, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = 1438915558;

    /**
     * Setter for <code>vnw_core.tbluser_reminder.reminder_id</code>.
     */
    public void setReminderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.reminder_id</code>.
     */
    public Integer getReminderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.activity</code>.
     */
    public void setActivity(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.activity</code>.
     */
    public String getActivity() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.data_id</code>.
     */
    public void setDataId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.data_id</code>.
     */
    public Integer getDataId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.data_type</code>.
     */
    public void setDataType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.data_type</code>.
     */
    public String getDataType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.noofdays</code>.
     */
    public void setNoofdays(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.noofdays</code>.
     */
    public Integer getNoofdays() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.sendingdate</code>.
     */
    public void setSendingdate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.sendingdate</code>.
     */
    public Timestamp getSendingdate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>vnw_core.tbluser_reminder.noofsent</code>.
     */
    public void setNoofsent(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>vnw_core.tbluser_reminder.noofsent</code>.
     */
    public Integer getNoofsent() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, String, Integer, Timestamp, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, String, Integer, Timestamp, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbluserReminder.TBLUSER_REMINDER.REMINDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbluserReminder.TBLUSER_REMINDER.ACTIVITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbluserReminder.TBLUSER_REMINDER.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TbluserReminder.TBLUSER_REMINDER.DATA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbluserReminder.TBLUSER_REMINDER.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TbluserReminder.TBLUSER_REMINDER.NOOFDAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TbluserReminder.TBLUSER_REMINDER.SENDINGDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TbluserReminder.TBLUSER_REMINDER.NOOFSENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getReminderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getActivity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getNoofdays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getSendingdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getNoofsent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value1(Integer value) {
        setReminderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value2(String value) {
        setActivity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value4(Integer value) {
        setDataId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value5(String value) {
        setDataType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value6(Integer value) {
        setNoofdays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value7(Timestamp value) {
        setSendingdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord value8(Integer value) {
        setNoofsent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbluserReminderRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, Timestamp value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbluserReminderRecord
     */
    public TbluserReminderRecord() {
        super(TbluserReminder.TBLUSER_REMINDER);
    }

    /**
     * Create a detached, initialised TbluserReminderRecord
     */
    public TbluserReminderRecord(Integer reminderId, String activity, String description, Integer dataId, String dataType, Integer noofdays, Timestamp sendingdate, Integer noofsent) {
        super(TbluserReminder.TBLUSER_REMINDER);

        set(0, reminderId);
        set(1, activity);
        set(2, description);
        set(3, dataId);
        set(4, dataType);
        set(5, noofdays);
        set(6, sendingdate);
        set(7, noofsent);
    }
}
