/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblemployerTemplateDefaultRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblemployerTemplateDefault extends TableImpl<TblemployerTemplateDefaultRecord> {

    private static final long serialVersionUID = -1822942445;

    /**
     * The reference instance of <code>vnw_core.tblemployer_template_default</code>
     */
    public static final TblemployerTemplateDefault TBLEMPLOYER_TEMPLATE_DEFAULT = new TblemployerTemplateDefault();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblemployerTemplateDefaultRecord> getRecordType() {
        return TblemployerTemplateDefaultRecord.class;
    }

    /**
     * The column <code>vnw_core.tblemployer_template_default.defaulttemplateid</code>.
     */
    public final TableField<TblemployerTemplateDefaultRecord, Byte> DEFAULTTEMPLATEID = createField("defaulttemplateid", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblemployer_template_default.languageid</code>. 1:VN; 2: EN
     */
    public final TableField<TblemployerTemplateDefaultRecord, Byte> LANGUAGEID = createField("languageid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.TINYINT)), this, "1:VN; 2: EN");

    /**
     * The column <code>vnw_core.tblemployer_template_default.templatetitle</code>.
     */
    public final TableField<TblemployerTemplateDefaultRecord, String> TEMPLATETITLE = createField("templatetitle", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>vnw_core.tblemployer_template_default.templatetypeid</code>. AS templatetypeid in tblemployer_template
     */
    public final TableField<TblemployerTemplateDefaultRecord, Byte> TEMPLATETYPEID = createField("templatetypeid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "AS templatetypeid in tblemployer_template");

    /**
     * The column <code>vnw_core.tblemployer_template_default.templatesubject</code>.
     */
    public final TableField<TblemployerTemplateDefaultRecord, String> TEMPLATESUBJECT = createField("templatesubject", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>vnw_core.tblemployer_template_default.templatecontent</code>.
     */
    public final TableField<TblemployerTemplateDefaultRecord, String> TEMPLATECONTENT = createField("templatecontent", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblemployer_template_default.createddate</code>.
     */
    public final TableField<TblemployerTemplateDefaultRecord, Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>vnw_core.tblemployer_template_default.updateddate</code>.
     */
    public final TableField<TblemployerTemplateDefaultRecord, Timestamp> UPDATEDDATE = createField("updateddate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>vnw_core.tblemployer_template_default</code> table reference
     */
    public TblemployerTemplateDefault() {
        this("tblemployer_template_default", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblemployer_template_default</code> table reference
     */
    public TblemployerTemplateDefault(String alias) {
        this(alias, TBLEMPLOYER_TEMPLATE_DEFAULT);
    }

    private TblemployerTemplateDefault(String alias, Table<TblemployerTemplateDefaultRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblemployerTemplateDefault(String alias, Table<TblemployerTemplateDefaultRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblemployerTemplateDefaultRecord> getPrimaryKey() {
        return Keys.KEY_TBLEMPLOYER_TEMPLATE_DEFAULT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblemployerTemplateDefaultRecord>> getKeys() {
        return Arrays.<UniqueKey<TblemployerTemplateDefaultRecord>>asList(Keys.KEY_TBLEMPLOYER_TEMPLATE_DEFAULT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblemployerTemplateDefault as(String alias) {
        return new TblemployerTemplateDefault(alias, this);
    }

    /**
     * Rename this table
     */
    public TblemployerTemplateDefault rename(String name) {
        return new TblemployerTemplateDefault(name, null);
    }
}
