/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblEventsMarcRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventsMarc extends TableImpl<TblEventsMarcRecord> {

    private static final long serialVersionUID = 1740421175;

    /**
     * The reference instance of <code>vnw_core.tbl_events_marc</code>
     */
    public static final TblEventsMarc TBL_EVENTS_MARC = new TblEventsMarc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblEventsMarcRecord> getRecordType() {
        return TblEventsMarcRecord.class;
    }

    /**
     * The column <code>vnw_core.tbl_events_marc.page_name</code>.
     */
    public final TableField<TblEventsMarcRecord, String> PAGE_NAME = createField("page_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>vnw_core.tbl_events_marc.page_view</code>.
     */
    public final TableField<TblEventsMarcRecord, Integer> PAGE_VIEW = createField("page_view", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>vnw_core.tbl_events_marc</code> table reference
     */
    public TblEventsMarc() {
        this("tbl_events_marc", null);
    }

    /**
     * Create an aliased <code>vnw_core.tbl_events_marc</code> table reference
     */
    public TblEventsMarc(String alias) {
        this(alias, TBL_EVENTS_MARC);
    }

    private TblEventsMarc(String alias, Table<TblEventsMarcRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblEventsMarc(String alias, Table<TblEventsMarcRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblEventsMarcRecord> getPrimaryKey() {
        return Keys.KEY_TBL_EVENTS_MARC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblEventsMarcRecord>> getKeys() {
        return Arrays.<UniqueKey<TblEventsMarcRecord>>asList(Keys.KEY_TBL_EVENTS_MARC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventsMarc as(String alias) {
        return new TblEventsMarc(alias, this);
    }

    /**
     * Rename this table
     */
    public TblEventsMarc rename(String name) {
        return new TblEventsMarc(name, null);
    }
}
