/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblemployerFolderRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblemployerFolder extends TableImpl<TblemployerFolderRecord> {

    private static final long serialVersionUID = -476227881;

    /**
     * The reference instance of <code>vnw_core.tblemployer_folder</code>
     */
    public static final TblemployerFolder TBLEMPLOYER_FOLDER = new TblemployerFolder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblemployerFolderRecord> getRecordType() {
        return TblemployerFolderRecord.class;
    }

    /**
     * The column <code>vnw_core.tblemployer_folder.folder_id</code>.
     */
    public final TableField<TblemployerFolderRecord, UInteger> FOLDER_ID = createField("folder_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblemployer_folder.userid</code>.
     */
    public final TableField<TblemployerFolderRecord, Integer> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>vnw_core.tblemployer_folder.folder_name</code>.
     */
    public final TableField<TblemployerFolderRecord, String> FOLDER_NAME = createField("folder_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>vnw_core.tblemployer_folder.folder_type</code>. 1: Job application. 2: Resume searching
     */
    public final TableField<TblemployerFolderRecord, UByte> FOLDER_TYPE = createField("folder_type", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "1: Job application. 2: Resume searching");

    /**
     * The column <code>vnw_core.tblemployer_folder.folder_totalunreadresume</code>.
     */
    public final TableField<TblemployerFolderRecord, UShort> FOLDER_TOTALUNREADRESUME = createField("folder_totalunreadresume", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.tblemployer_folder.folder_totalresume</code>.
     */
    public final TableField<TblemployerFolderRecord, UShort> FOLDER_TOTALRESUME = createField("folder_totalresume", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.tblemployer_folder.folder_createdate</code>.
     */
    public final TableField<TblemployerFolderRecord, Timestamp> FOLDER_CREATEDATE = createField("folder_createdate", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>vnw_core.tblemployer_folder</code> table reference
     */
    public TblemployerFolder() {
        this("tblemployer_folder", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblemployer_folder</code> table reference
     */
    public TblemployerFolder(String alias) {
        this(alias, TBLEMPLOYER_FOLDER);
    }

    private TblemployerFolder(String alias, Table<TblemployerFolderRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblemployerFolder(String alias, Table<TblemployerFolderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblemployerFolderRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_TBLEMPLOYER_FOLDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblemployerFolderRecord> getPrimaryKey() {
        return Keys.KEY_TBLEMPLOYER_FOLDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblemployerFolderRecord>> getKeys() {
        return Arrays.<UniqueKey<TblemployerFolderRecord>>asList(Keys.KEY_TBLEMPLOYER_FOLDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblemployerFolder as(String alias) {
        return new TblemployerFolder(alias, this);
    }

    /**
     * Rename this table
     */
    public TblemployerFolder rename(String name) {
        return new TblemployerFolder(name, null);
    }
}
