/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefProficiencyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefProficiency extends TableImpl<TblrefProficiencyRecord> {

    private static final long serialVersionUID = -1832524676;

    /**
     * The reference instance of <code>vnw_core.tblref_proficiency</code>
     */
    public static final TblrefProficiency TBLREF_PROFICIENCY = new TblrefProficiency();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefProficiencyRecord> getRecordType() {
        return TblrefProficiencyRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_proficiency.proficiency_id</code>.
     */
    public final TableField<TblrefProficiencyRecord, Byte> PROFICIENCY_ID = createField("proficiency_id", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblref_proficiency.languageid</code>.
     */
    public final TableField<TblrefProficiencyRecord, Byte> LANGUAGEID = createField("languageid", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblref_proficiency.proficiency_name</code>.
     */
    public final TableField<TblrefProficiencyRecord, String> PROFICIENCY_NAME = createField("proficiency_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.tblref_proficiency.proficiency_order</code>.
     */
    public final TableField<TblrefProficiencyRecord, Short> PROFICIENCY_ORDER = createField("proficiency_order", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>vnw_core.tblref_proficiency</code> table reference
     */
    public TblrefProficiency() {
        this("tblref_proficiency", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_proficiency</code> table reference
     */
    public TblrefProficiency(String alias) {
        this(alias, TBLREF_PROFICIENCY);
    }

    private TblrefProficiency(String alias, Table<TblrefProficiencyRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefProficiency(String alias, Table<TblrefProficiencyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefProficiencyRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_PROFICIENCY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefProficiencyRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefProficiencyRecord>>asList(Keys.KEY_TBLREF_PROFICIENCY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefProficiency as(String alias) {
        return new TblrefProficiency(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefProficiency rename(String name) {
        return new TblrefProficiency(name, null);
    }
}
