/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefActiontypecodeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefActiontypecode extends TableImpl<TblrefActiontypecodeRecord> {

    private static final long serialVersionUID = -579375084;

    /**
     * The reference instance of <code>vnw_core.tblref_actiontypecode</code>
     */
    public static final TblrefActiontypecode TBLREF_ACTIONTYPECODE = new TblrefActiontypecode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefActiontypecodeRecord> getRecordType() {
        return TblrefActiontypecodeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_actiontypecode.actiontypeid</code>.
     */
    public final TableField<TblrefActiontypecodeRecord, Short> ACTIONTYPEID = createField("actiontypeid", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblref_actiontypecode.actiontypecode</code>.
     */
    public final TableField<TblrefActiontypecodeRecord, String> ACTIONTYPECODE = createField("actiontypecode", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>vnw_core.tblref_actiontypecode</code> table reference
     */
    public TblrefActiontypecode() {
        this("tblref_actiontypecode", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_actiontypecode</code> table reference
     */
    public TblrefActiontypecode(String alias) {
        this(alias, TBLREF_ACTIONTYPECODE);
    }

    private TblrefActiontypecode(String alias, Table<TblrefActiontypecodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefActiontypecode(String alias, Table<TblrefActiontypecodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblrefActiontypecodeRecord, Short> getIdentity() {
        return Keys.IDENTITY_TBLREF_ACTIONTYPECODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefActiontypecodeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_ACTIONTYPECODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefActiontypecodeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefActiontypecodeRecord>>asList(Keys.KEY_TBLREF_ACTIONTYPECODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefActiontypecode as(String alias) {
        return new TblrefActiontypecode(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefActiontypecode rename(String name) {
        return new TblrefActiontypecode(name, null);
    }
}
