/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefActiontypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefActiontype extends TableImpl<TblrefActiontypeRecord> {

    private static final long serialVersionUID = 725839234;

    /**
     * The reference instance of <code>vnw_core.tblref_actiontype</code>
     */
    public static final TblrefActiontype TBLREF_ACTIONTYPE = new TblrefActiontype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefActiontypeRecord> getRecordType() {
        return TblrefActiontypeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_actiontype.actiontypeid</code>.
     */
    public final TableField<TblrefActiontypeRecord, Short> ACTIONTYPEID = createField("actiontypeid", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_actiontype.languageid</code>.
     */
    public final TableField<TblrefActiontypeRecord, Byte> LANGUAGEID = createField("languageid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_actiontype.actiontypename</code>.
     */
    public final TableField<TblrefActiontypeRecord, String> ACTIONTYPENAME = createField("actiontypename", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.tblref_actiontype.actiontypeorder</code>.
     */
    public final TableField<TblrefActiontypeRecord, Short> ACTIONTYPEORDER = createField("actiontypeorder", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>vnw_core.tblref_actiontype</code> table reference
     */
    public TblrefActiontype() {
        this("tblref_actiontype", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_actiontype</code> table reference
     */
    public TblrefActiontype(String alias) {
        this(alias, TBLREF_ACTIONTYPE);
    }

    private TblrefActiontype(String alias, Table<TblrefActiontypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefActiontype(String alias, Table<TblrefActiontypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefActiontypeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_ACTIONTYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefActiontypeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefActiontypeRecord>>asList(Keys.KEY_TBLREF_ACTIONTYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefActiontype as(String alias) {
        return new TblrefActiontype(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefActiontype rename(String name) {
        return new TblrefActiontype(name, null);
    }
}
