/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefHighestdegreeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefHighestdegree extends TableImpl<TblrefHighestdegreeRecord> {

    private static final long serialVersionUID = -604410124;

    /**
     * The reference instance of <code>vnw_core.tblref_highestdegree</code>
     */
    public static final TblrefHighestdegree TBLREF_HIGHESTDEGREE = new TblrefHighestdegree();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefHighestdegreeRecord> getRecordType() {
        return TblrefHighestdegreeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_highestdegree.highestdegreeid</code>.
     */
    public final TableField<TblrefHighestdegreeRecord, Byte> HIGHESTDEGREEID = createField("highestdegreeid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_highestdegree.languageid</code>.
     */
    public final TableField<TblrefHighestdegreeRecord, Byte> LANGUAGEID = createField("languageid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_highestdegree.highestdegreename</code>.
     */
    public final TableField<TblrefHighestdegreeRecord, String> HIGHESTDEGREENAME = createField("highestdegreename", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.tblref_highestdegree.highestdegreeorder</code>.
     */
    public final TableField<TblrefHighestdegreeRecord, Byte> HIGHESTDEGREEORDER = createField("highestdegreeorder", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>vnw_core.tblref_highestdegree.weight</code>.
     */
    public final TableField<TblrefHighestdegreeRecord, Byte> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>vnw_core.tblref_highestdegree.isexact</code>.
     */
    public final TableField<TblrefHighestdegreeRecord, Byte> ISEXACT = createField("isexact", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>vnw_core.tblref_highestdegree</code> table reference
     */
    public TblrefHighestdegree() {
        this("tblref_highestdegree", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_highestdegree</code> table reference
     */
    public TblrefHighestdegree(String alias) {
        this(alias, TBLREF_HIGHESTDEGREE);
    }

    private TblrefHighestdegree(String alias, Table<TblrefHighestdegreeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefHighestdegree(String alias, Table<TblrefHighestdegreeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefHighestdegreeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_HIGHESTDEGREE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefHighestdegreeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefHighestdegreeRecord>>asList(Keys.KEY_TBLREF_HIGHESTDEGREE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefHighestdegree as(String alias) {
        return new TblrefHighestdegree(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefHighestdegree rename(String name) {
        return new TblrefHighestdegree(name, null);
    }
}
