/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefPublicationcodeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefPublicationcode extends TableImpl<TblrefPublicationcodeRecord> {

    private static final long serialVersionUID = -1844799084;

    /**
     * The reference instance of <code>vnw_core.tblref_publicationcode</code>
     */
    public static final TblrefPublicationcode TBLREF_PUBLICATIONCODE = new TblrefPublicationcode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefPublicationcodeRecord> getRecordType() {
        return TblrefPublicationcodeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_publicationcode.publicationid</code>.
     */
    public final TableField<TblrefPublicationcodeRecord, Byte> PUBLICATIONID = createField("publicationid", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblref_publicationcode.publicationcode</code>.
     */
    public final TableField<TblrefPublicationcodeRecord, String> PUBLICATIONCODE = createField("publicationcode", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>vnw_core.tblref_publicationcode</code> table reference
     */
    public TblrefPublicationcode() {
        this("tblref_publicationcode", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_publicationcode</code> table reference
     */
    public TblrefPublicationcode(String alias) {
        this(alias, TBLREF_PUBLICATIONCODE);
    }

    private TblrefPublicationcode(String alias, Table<TblrefPublicationcodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefPublicationcode(String alias, Table<TblrefPublicationcodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblrefPublicationcodeRecord, Byte> getIdentity() {
        return Keys.IDENTITY_TBLREF_PUBLICATIONCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefPublicationcodeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_PUBLICATIONCODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefPublicationcodeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefPublicationcodeRecord>>asList(Keys.KEY_TBLREF_PUBLICATIONCODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefPublicationcode as(String alias) {
        return new TblrefPublicationcode(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefPublicationcode rename(String name) {
        return new TblrefPublicationcode(name, null);
    }
}
