/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefIndustrycodeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefIndustrycode extends TableImpl<TblrefIndustrycodeRecord> {

    private static final long serialVersionUID = -1998486667;

    /**
     * The reference instance of <code>vnw_core.tblref_industrycode</code>
     */
    public static final TblrefIndustrycode TBLREF_INDUSTRYCODE = new TblrefIndustrycode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefIndustrycodeRecord> getRecordType() {
        return TblrefIndustrycodeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_industrycode.industryid</code>.
     */
    public final TableField<TblrefIndustrycodeRecord, Short> INDUSTRYID = createField("industryid", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblref_industrycode.industrycode</code>.
     */
    public final TableField<TblrefIndustrycodeRecord, String> INDUSTRYCODE = createField("industrycode", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>vnw_core.tblref_industrycode.industryjobcount</code>.
     */
    public final TableField<TblrefIndustrycodeRecord, Integer> INDUSTRYJOBCOUNT = createField("industryjobcount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>vnw_core.tblref_industrycode.industryresumecount</code>.
     */
    public final TableField<TblrefIndustrycodeRecord, Integer> INDUSTRYRESUMECOUNT = createField("industryresumecount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>vnw_core.tblref_industrycode</code> table reference
     */
    public TblrefIndustrycode() {
        this("tblref_industrycode", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_industrycode</code> table reference
     */
    public TblrefIndustrycode(String alias) {
        this(alias, TBLREF_INDUSTRYCODE);
    }

    private TblrefIndustrycode(String alias, Table<TblrefIndustrycodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefIndustrycode(String alias, Table<TblrefIndustrycodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblrefIndustrycodeRecord, Short> getIdentity() {
        return Keys.IDENTITY_TBLREF_INDUSTRYCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefIndustrycodeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_INDUSTRYCODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefIndustrycodeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefIndustrycodeRecord>>asList(Keys.KEY_TBLREF_INDUSTRYCODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefIndustrycode as(String alias) {
        return new TblrefIndustrycode(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefIndustrycode rename(String name) {
        return new TblrefIndustrycode(name, null);
    }
}
