/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefSchoolRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefSchool extends TableImpl<TblrefSchoolRecord> {

    private static final long serialVersionUID = -1748776578;

    /**
     * The reference instance of <code>vnw_core.tblref_school</code>
     */
    public static final TblrefSchool TBLREF_SCHOOL = new TblrefSchool();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefSchoolRecord> getRecordType() {
        return TblrefSchoolRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_school.schoolid</code>.
     */
    public final TableField<TblrefSchoolRecord, Short> SCHOOLID = createField("schoolid", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_school.languageid</code>.
     */
    public final TableField<TblrefSchoolRecord, Byte> LANGUAGEID = createField("languageid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_school.schoolname</code>.
     */
    public final TableField<TblrefSchoolRecord, String> SCHOOLNAME = createField("schoolname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.tblref_school.schoolorder</code>.
     */
    public final TableField<TblrefSchoolRecord, Short> SCHOOLORDER = createField("schoolorder", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>vnw_core.tblref_school</code> table reference
     */
    public TblrefSchool() {
        this("tblref_school", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_school</code> table reference
     */
    public TblrefSchool(String alias) {
        this(alias, TBLREF_SCHOOL);
    }

    private TblrefSchool(String alias, Table<TblrefSchoolRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefSchool(String alias, Table<TblrefSchoolRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefSchoolRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_SCHOOL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefSchoolRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefSchoolRecord>>asList(Keys.KEY_TBLREF_SCHOOL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefSchool as(String alias) {
        return new TblrefSchool(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefSchool rename(String name) {
        return new TblrefSchool(name, null);
    }
}
