/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblresumeUpgradingByuserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Count resume that intermship upgraded
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblresumeUpgradingByuser extends TableImpl<TblresumeUpgradingByuserRecord> {

    private static final long serialVersionUID = -1003697073;

    /**
     * The reference instance of <code>vnw_core.tblresume_upgrading_byuser</code>
     */
    public static final TblresumeUpgradingByuser TBLRESUME_UPGRADING_BYUSER = new TblresumeUpgradingByuser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblresumeUpgradingByuserRecord> getRecordType() {
        return TblresumeUpgradingByuserRecord.class;
    }

    /**
     * The column <code>vnw_core.tblresume_upgrading_byuser.userid</code>.
     */
    public final TableField<TblresumeUpgradingByuserRecord, Integer> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblresume_upgrading_byuser.resumeid</code>.
     */
    public final TableField<TblresumeUpgradingByuserRecord, Integer> RESUMEID = createField("resumeid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblresume_upgrading_byuser.dateupgraded</code>.
     */
    public final TableField<TblresumeUpgradingByuserRecord, Timestamp> DATEUPGRADED = createField("dateupgraded", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>vnw_core.tblresume_upgrading_byuser</code> table reference
     */
    public TblresumeUpgradingByuser() {
        this("tblresume_upgrading_byuser", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblresume_upgrading_byuser</code> table reference
     */
    public TblresumeUpgradingByuser(String alias) {
        this(alias, TBLRESUME_UPGRADING_BYUSER);
    }

    private TblresumeUpgradingByuser(String alias, Table<TblresumeUpgradingByuserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblresumeUpgradingByuser(String alias, Table<TblresumeUpgradingByuserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Count resume that intermship upgraded");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblresumeUpgradingByuserRecord> getPrimaryKey() {
        return Keys.KEY_TBLRESUME_UPGRADING_BYUSER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblresumeUpgradingByuserRecord>> getKeys() {
        return Arrays.<UniqueKey<TblresumeUpgradingByuserRecord>>asList(Keys.KEY_TBLRESUME_UPGRADING_BYUSER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblresumeUpgradingByuser as(String alias) {
        return new TblresumeUpgradingByuser(alias, this);
    }

    /**
     * Rename this table
     */
    public TblresumeUpgradingByuser rename(String name) {
        return new TblresumeUpgradingByuser(name, null);
    }
}
