/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefResumestatuscodeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefResumestatuscode extends TableImpl<TblrefResumestatuscodeRecord> {

    private static final long serialVersionUID = 1998512310;

    /**
     * The reference instance of <code>vnw_core.tblref_resumestatuscode</code>
     */
    public static final TblrefResumestatuscode TBLREF_RESUMESTATUSCODE = new TblrefResumestatuscode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefResumestatuscodeRecord> getRecordType() {
        return TblrefResumestatuscodeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_resumestatuscode.resumestatus_id</code>.
     */
    public final TableField<TblrefResumestatuscodeRecord, UByte> RESUMESTATUS_ID = createField("resumestatus_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tblref_resumestatuscode.resumestatus_code</code>.
     */
    public final TableField<TblrefResumestatuscodeRecord, String> RESUMESTATUS_CODE = createField("resumestatus_code", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>vnw_core.tblref_resumestatuscode</code> table reference
     */
    public TblrefResumestatuscode() {
        this("tblref_resumestatuscode", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_resumestatuscode</code> table reference
     */
    public TblrefResumestatuscode(String alias) {
        this(alias, TBLREF_RESUMESTATUSCODE);
    }

    private TblrefResumestatuscode(String alias, Table<TblrefResumestatuscodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefResumestatuscode(String alias, Table<TblrefResumestatuscodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblrefResumestatuscodeRecord, UByte> getIdentity() {
        return Keys.IDENTITY_TBLREF_RESUMESTATUSCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefResumestatuscodeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_RESUMESTATUSCODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefResumestatuscodeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefResumestatuscodeRecord>>asList(Keys.KEY_TBLREF_RESUMESTATUSCODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefResumestatuscode as(String alias) {
        return new TblrefResumestatuscode(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefResumestatuscode rename(String name) {
        return new TblrefResumestatuscode(name, null);
    }
}
