/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TblrefSalaryrangeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblrefSalaryrange extends TableImpl<TblrefSalaryrangeRecord> {

    private static final long serialVersionUID = -1360472516;

    /**
     * The reference instance of <code>vnw_core.tblref_salaryrange</code>
     */
    public static final TblrefSalaryrange TBLREF_SALARYRANGE = new TblrefSalaryrange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblrefSalaryrangeRecord> getRecordType() {
        return TblrefSalaryrangeRecord.class;
    }

    /**
     * The column <code>vnw_core.tblref_salaryrange.salaryrangeid</code>.
     */
    public final TableField<TblrefSalaryrangeRecord, Byte> SALARYRANGEID = createField("salaryrangeid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_salaryrange.languageid</code>.
     */
    public final TableField<TblrefSalaryrangeRecord, Byte> LANGUAGEID = createField("languageid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>vnw_core.tblref_salaryrange.salaryrangename</code>.
     */
    public final TableField<TblrefSalaryrangeRecord, String> SALARYRANGENAME = createField("salaryrangename", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.tblref_salaryrange.salaryrangeorder</code>.
     */
    public final TableField<TblrefSalaryrangeRecord, Byte> SALARYRANGEORDER = createField("salaryrangeorder", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>vnw_core.tblref_salaryrange</code> table reference
     */
    public TblrefSalaryrange() {
        this("tblref_salaryrange", null);
    }

    /**
     * Create an aliased <code>vnw_core.tblref_salaryrange</code> table reference
     */
    public TblrefSalaryrange(String alias) {
        this(alias, TBLREF_SALARYRANGE);
    }

    private TblrefSalaryrange(String alias, Table<TblrefSalaryrangeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblrefSalaryrange(String alias, Table<TblrefSalaryrangeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblrefSalaryrangeRecord> getPrimaryKey() {
        return Keys.KEY_TBLREF_SALARYRANGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblrefSalaryrangeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblrefSalaryrangeRecord>>asList(Keys.KEY_TBLREF_SALARYRANGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblrefSalaryrange as(String alias) {
        return new TblrefSalaryrange(alias, this);
    }

    /**
     * Rename this table
     */
    public TblrefSalaryrange rename(String name) {
        return new TblrefSalaryrange(name, null);
    }
}
