/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TbltrackLogin_0Record;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbltrackLogin_0 extends TableImpl<TbltrackLogin_0Record> {

    private static final long serialVersionUID = -1147762527;

    /**
     * The reference instance of <code>vnw_core.tbltrack_login_0</code>
     */
    public static final TbltrackLogin_0 TBLTRACK_LOGIN_0 = new TbltrackLogin_0();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbltrackLogin_0Record> getRecordType() {
        return TbltrackLogin_0Record.class;
    }

    /**
     * The column <code>vnw_core.tbltrack_login_0.userid</code>.
     */
    public final TableField<TbltrackLogin_0Record, UInteger> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tbltrack_login_0.username</code>.
     */
    public final TableField<TbltrackLogin_0Record, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>vnw_core.tbltrack_login_0.youareid</code>.
     */
    public final TableField<TbltrackLogin_0Record, UByte> YOUAREID = createField("youareid", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tbltrack_login_0.loginTime</code>.
     */
    public final TableField<TbltrackLogin_0Record, Timestamp> LOGINTIME = createField("loginTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>vnw_core.tbltrack_login_0.sessionId</code>.
     */
    public final TableField<TbltrackLogin_0Record, String> SESSIONID = createField("sessionId", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>vnw_core.tbltrack_login_0.loginbyid</code>.  1: vietnamworks  2: Facebook  3: Google  4: Linkedin 
     */
    public final TableField<TbltrackLogin_0Record, Byte> LOGINBYID = createField("loginbyid", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.TINYINT)), this, " 1: vietnamworks  2: Facebook  3: Google  4: Linkedin ");

    /**
     * Create a <code>vnw_core.tbltrack_login_0</code> table reference
     */
    public TbltrackLogin_0() {
        this("tbltrack_login_0", null);
    }

    /**
     * Create an aliased <code>vnw_core.tbltrack_login_0</code> table reference
     */
    public TbltrackLogin_0(String alias) {
        this(alias, TBLTRACK_LOGIN_0);
    }

    private TbltrackLogin_0(String alias, Table<TbltrackLogin_0Record> aliased) {
        this(alias, aliased, null);
    }

    private TbltrackLogin_0(String alias, Table<TbltrackLogin_0Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbltrackLogin_0 as(String alias) {
        return new TbltrackLogin_0(alias, this);
    }

    /**
     * Rename this table
     */
    public TbltrackLogin_0 rename(String name) {
        return new TbltrackLogin_0(name, null);
    }
}
