/**
 * This class is generated by jOOQ
 */
package com.vnw.data.jooq.tables;


import com.vnw.data.jooq.Keys;
import com.vnw.data.jooq.VnwCore;
import com.vnw.data.jooq.tables.records.TrackJobSearchRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackJobSearch extends TableImpl<TrackJobSearchRecord> {

    private static final long serialVersionUID = -1201808507;

    /**
     * The reference instance of <code>vnw_core.track_job_search</code>
     */
    public static final TrackJobSearch TRACK_JOB_SEARCH = new TrackJobSearch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackJobSearchRecord> getRecordType() {
        return TrackJobSearchRecord.class;
    }

    /**
     * The column <code>vnw_core.track_job_search.id</code>.
     */
    public final TableField<TrackJobSearchRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>vnw_core.track_job_search.user_id</code>.
     */
    public final TableField<TrackJobSearchRecord, UInteger> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.keywords</code>.
     */
    public final TableField<TrackJobSearchRecord, String> KEYWORDS = createField("keywords", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.track_job_search.mustmatch_id</code>.
     */
    public final TableField<TrackJobSearchRecord, UByte> MUSTMATCH_ID = createField("mustmatch_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.industry_id</code>.
     */
    public final TableField<TrackJobSearchRecord, String> INDUSTRY_ID = createField("industry_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.track_job_search.salary_min</code>.
     */
    public final TableField<TrackJobSearchRecord, String> SALARY_MIN = createField("salary_min", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.track_job_search.salary_max</code>.
     */
    public final TableField<TrackJobSearchRecord, String> SALARY_MAX = createField("salary_max", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>vnw_core.track_job_search.city_id</code>.
     */
    public final TableField<TrackJobSearchRecord, UInteger> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.typeworking_id</code>.
     */
    public final TableField<TrackJobSearchRecord, UByte> TYPEWORKING_ID = createField("typeworking_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.joblevel_id</code>.
     */
    public final TableField<TrackJobSearchRecord, UByte> JOBLEVEL_ID = createField("joblevel_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.degree_id</code>.
     */
    public final TableField<TrackJobSearchRecord, UByte> DEGREE_ID = createField("degree_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.years_experience</code>.
     */
    public final TableField<TrackJobSearchRecord, UByte> YEARS_EXPERIENCE = createField("years_experience", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.day_job_posted</code>.
     */
    public final TableField<TrackJobSearchRecord, UByte> DAY_JOB_POSTED = createField("day_job_posted", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column <code>vnw_core.track_job_search.create_at</code>.
     */
    public final TableField<TrackJobSearchRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>vnw_core.track_job_search</code> table reference
     */
    public TrackJobSearch() {
        this("track_job_search", null);
    }

    /**
     * Create an aliased <code>vnw_core.track_job_search</code> table reference
     */
    public TrackJobSearch(String alias) {
        this(alias, TRACK_JOB_SEARCH);
    }

    private TrackJobSearch(String alias, Table<TrackJobSearchRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrackJobSearch(String alias, Table<TrackJobSearchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VnwCore.VNW_CORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TrackJobSearchRecord, ULong> getIdentity() {
        return Keys.IDENTITY_TRACK_JOB_SEARCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TrackJobSearchRecord> getPrimaryKey() {
        return Keys.KEY_TRACK_JOB_SEARCH_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TrackJobSearchRecord>> getKeys() {
        return Arrays.<UniqueKey<TrackJobSearchRecord>>asList(Keys.KEY_TRACK_JOB_SEARCH_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrackJobSearch as(String alias) {
        return new TrackJobSearch(alias, this);
    }

    /**
     * Rename this table
     */
    public TrackJobSearch rename(String name) {
        return new TrackJobSearch(name, null);
    }
}
